<?php
/*
*
* Language file for Help Desk Software HESK (https://www.hesk.com)
* Language: Japanese
* Version: 3.2.0
*
* ==> CONTRIBUTORS
*
* Klemen Stirn (https://www.hesk.com)
* Mike Koch (https://mikeko.ch)
*
* ==> HOW TO TRANSLATE THIS FILE
*
* https://www.hesk.com/knowledgebase/?article=34
*
* ==> HOW TO CUSTOMIZE TEXT
*
* Do NOT customize text inside here, it will be overwritten by updates!
*
* Follow this guide instead:
* https://www.hesk.com/knowledgebase/?article=88
*
* ==> IMPORTANT: FILE ENCODING
*
* This file *must* be saved in UTF-8 encoding without byte order mark (BOM)
* Test chars: àáâãäåæ
*
* https://www.hesk.com/knowledgebase/?article=87
*
*/

// Native name of language, for example: Deutsch
$hesklang['LANGUAGE']='Japanese';

// English name of language, for example: German
$hesklang['LANGUAGE_JA']='Japanese';

// Language encoding. It MUST be set to UTF-8 for all languages!
$hesklang['ENCODING']='UTF-8';

// MySQL utf8 collation. Do not change if not sure what to use.
$hesklang['_COLLATE']='utf8_unicode_ci';

// This is the email break line that will be used in email piping
$hesklang['EMAIL_HR']='------ Reply above this line ------';

// EMAIL SUBJECTS
$hesklang['new_ticket_staff']       = '[#%%TRACK_ID%%] 新しいチケット: %%SUBJECT%%';
$hesklang['ticket_received']        = '[#%%TRACK_ID%%] チケットの受取: %%SUBJECT%%';
$hesklang['ticket_assigned_to_you']='[#%%TRACK_ID%%] チケットの割り当て: %%SUBJECT%%';
$hesklang['new_reply_by_customer']  = '[#%%TRACK_ID%%] 新しい返信: %%SUBJECT%%';
$hesklang['new_reply_by_staff']     = '[#%%TRACK_ID%%] 新しい返信: %%SUBJECT%%';
$hesklang['category_moved']         = '[#%%TRACK_ID%%] チケットの移動: %%SUBJECT%%';
$hesklang['new_note']               = '[#%%TRACK_ID%%] 注記を追加しました。: %%SUBJECT%%';
$hesklang['new_pm']                 = '新しい個別メッセージ: %%SUBJECT%%';
$hesklang['forgot_ticket_id']       = 'サポートチケットの一覧';
$hesklang['ticket_closed']			= '[#%%TRACK_ID%%] チケットクローズ/解決済み'; // New in 2.6.0
$hesklang['overdue_ticket']         = '[#%%TRACK_ID%%] チケットの期限切れ'; // New in 3.2.0
$hesklang['ticket_escalated']       = '[#%%TRACK_ID%%] エスカレート: %%SUBJECT%%'; // New in 3.2.0

// ERROR MESSAGES
$hesklang['cant_connect_db']='データベースに接続できない!';
$hesklang['invalid_action']='無効なアクション';
$hesklang['select_username']='ユーザー名を選択してください';
$hesklang['enter_pass']='パスワードを入力してください';
$hesklang['cant_sql']='SQLが実行できません';
$hesklang['contact_webmsater']='管理者までお知らせください。';
$hesklang['mysql_said']='MySQLは次のように述べています。';
$hesklang['wrong_pass']='Wrong password（パスワードが違います）';
$hesklang['session_expired']='あなたのセッションは期限切れです、下のフォームを使ってログインしてください。';
$hesklang['attempt']='無効な試みです!';
$hesklang['not_authorized_tickets']='このカテゴリー内のチケットを表示する権限がありません!';
$hesklang['must_be_admin']='このページを表示する権限がありません このページを表示するには、管理者としてログインする必要があります。';
$hesklang['no_session']='新しいセッションを開始できません!';
$hesklang['error']='エラー';
$hesklang['int_error']='Internal script error(内部スクリプトエラー)';
$hesklang['no_trackID']='トラッキングIDがありません';
$hesklang['status_not_valid']='ステータスが有効でない';
$hesklang['trackID_not_found']='トラッキングIDが見つかりませんでした';
$hesklang['select_priority']='優先度を選択してください';
$hesklang['ticket_not_found']='Ticket not found! 正しいトラッキングIDを入力したか確認してください!';
$hesklang['no_selected']='選択されたチケットはありません、何も変更することはありません';
$hesklang['id_not_valid']='このIDは有効ではありません';
$hesklang['enter_id']='トラッキングIDを入力してください';
$hesklang['enter_name']='顧客名を入力してください';
$hesklang['enter_date']='検索したい日付を入力してください';
$hesklang['date_not_valid']='This is not a valid date. 日付を<b>YYYY-MM-DD</b>のフォーマットで入力してください。';
$hesklang['enter_subject']='チケットの件名を入力してください';
$hesklang['invalid_search']='無効な検索アクション';
$hesklang['choose_cat_ren']='名前を変更するカテゴリを選択してください';
$hesklang['cat_ren_name']='新しいカテゴリー名を書いてください';
$hesklang['cat_not_found']='カテゴリが見つかりませんでした';
$hesklang['enter_cat_name']='カテゴリ名を入力してください';
$hesklang['no_cat_id']='カテゴリーIDがありません';
$hesklang['cant_del_default_cat']='デフォルトのカテゴリは削除できません、名前の変更のみ可能です';
$hesklang['no_valid_id']='有効なユーザIDがありません';
$hesklang['user_not_found']='ユーザが見つかりません';
$hesklang['enter_real_name']='ユーザー実名を入力してください';
$hesklang['enter_valid_email']='有効な電子メールアドレスを入力してください';
$hesklang['enter_username']='ユーザー名(ログイン)を入力してください';
$hesklang['asign_one_cat']='ユーザーを少なくとも1つのカテゴリに割り当ててください!';
$hesklang['confirm_user_pass']='パスワードを確認してください';
$hesklang['password_not_same']='入力された2つのパスワードは同じではありません!';
$hesklang['cant_del_admin']='デフォルトの管理者を削除できません!';
$hesklang['cant_del_own']='ログインしているプロファイルは削除できません!'; 
$hesklang['enter_your_name']='あなたの名前を入力してください';
$hesklang['enter_message']='メッセージを入力してください'; 
$hesklang['sel_app_cat']='適切なカテゴリを選択してください';
$hesklang['sel_app_priority']='適切な優先度を選択してください';
$hesklang['enter_ticket_subject']='チケットの件名を入力してください';
$hesklang['user_not_found_nothing_edit']='ユーザーが見つからないか、変更するものがありません';

// ADMIN PANEL
$hesklang['administrator']='管理者';
$hesklang['login']='ログイン';
$hesklang['user']='ユーザー';
$hesklang['username']='ユーザー名';
$hesklang['pass']='パスワード';
$hesklang['confirm_pass']='パスワードを確認';
$hesklang['logged_out']='ログアウト';
$hesklang['logout']='ログアウト';
$hesklang['logout_success']='ログアウトに成功しました。';
$hesklang['click_login']='ログインするにはここをクリックしてください';
$hesklang['back']='戻る';
$hesklang['displaying_pages']='チケットページを <b>%d</b> 表示する:';
$hesklang['trackID']='トラッキング ID';
$hesklang['timestamp']='タイムスタンプ';
$hesklang['name']='お名前';
$hesklang['subject']='件名';
$hesklang['status']='ステータス';
$hesklang['priority']='優先度';
$hesklang['open_action']='チケットを開く'; // Open ACTION
$hesklang['close']='チケットを終了'; // Closed ticket STATUS
$hesklang['any_status']='現在のステータス';
$hesklang['high']='高い';
$hesklang['medium']='普通';
$hesklang['low']='低い';
$hesklang['del_selected']='選択したチケットを消去';
$hesklang['manage_cat']='カテゴリーを管理';
$hesklang['profile']='あなたのプロフィール';
$hesklang['show_tickets']='チケットを見る';
$hesklang['sort_by']='Sort by';
$hesklang['date_posted']='投稿日';
$hesklang['category']='カテゴリー';
$hesklang['any_cat']='どのカテゴリーでもよい';
$hesklang['order']='順序';
$hesklang['ascending']='昇順';
$hesklang['descending']='降順';
$hesklang['display']='表示';
$hesklang['tets_page']='ページごとのチケット数';
$hesklang['find_ticket']='チケットの検索';
$hesklang['yyyy_mm_dd']='YYYY-MM-DD';
$hesklang['results_page']='1ページあたりの結果';
$hesklang['opened']='開く'; // チケットがOPENされました。
$hesklang['ticket']='チケット';
$hesklang['ticket']='チケット';
$hesklang['ticket_been']='このチケットは';
$hesklang['view_ticket']='チケットを見る';
$hesklang['open_tickets']='オープンチケット';
$hesklang['remove_statement']='&quot;Powered by&quot;ステートメントを削除する';
$hesklang['click_info']='詳しくはこちらをクリック';
$hesklang['reply_added']='返信を追加しました';
$hesklang['ticket_marked']='このチケットはマークされています';
$hesklang['ticket_status']='チケットの状態';
$hesklang['replies']='リプライ';
$hesklang['date']='日付';
$hesklang['email']='メール';
$hesklang['ip']='IP';
$hesklang['message']='メッセージ';
$hesklang['add_reply']='返信を追加する';
$hesklang['change_priority']='優先度を';
$hesklang['attach_sign']='署名を添付する';
$hesklang['profile_settings']='プロフィールの設定';
$hesklang['submit_reply']='返信を送信する';
$hesklang['support_panel']='サポートパネル';
$hesklang['ticket_trackID']='チケットの追跡ID';
$hesklang['c2c']='クリックで継続';
$hesklang['tets_deleted']='チケットは削除されました';
$hesklang['confirm_del_cat']='本当にこのカテゴリーを削除しますか';
$hesklang['remove']='削除';
$hesklang['max_chars']='最大40文字';
$hesklang['ren_cat']='カテゴリ名を変更する';
$hesklang['to']='宛先';
$hesklang['cat_added']='カテゴリを追加しました';
$hesklang['cat_name_added']='カテゴリ %s が正常に追加されました';
$hesklang['cat_renamed']='カテゴリの名前を変更しました';
$hesklang['cat_renamed_to']='選択されたカテゴリーは正常ににリネームされました';
$hesklang['cat_removed']='カテゴリが削除されました';
$hesklang['cat_removed_db']='選択されたカテゴリーは、データベースから正常に削除されました';
$hesklang['sure_remove_user']='本当にこのユーザーを削除しますか？';
$hesklang['manage_users']='ユーザーを管理する';
$hesklang['users_intro']='ここで、管理画面にログインできるユーザーと、管理画面にログインできないユーザーを管理することができます。
チケットに回答します。管理者は任意のカテゴリのチケットを表示/編集することができます。
管理画面のすべての機能（ユーザー管理、カテゴリー管理など）を利用できます。
他のユーザーは、自分のカテゴリー内のチケットのみ閲覧および返信することができます。';
$hesklang['yes']='はい';
$hesklang['no']='いいえ';
$hesklang['edit']='Edit(編集)';
$hesklang['add_user']='新しいユーザーを追加する';
$hesklang['req_marked_with']='必須項目は*でマークされています';
$hesklang['real_name']='本名';
$hesklang['sign_extra']='HTMLコードは許可されていません。リンクはクリックできるようにします';
$hesklang['create_user']='ユーザーを作成する';
$hesklang['editing_user']='ユーザーを編集する';
$hesklang['user_added']='ユーザーを追加しました';
$hesklang['user_added_success']='パスワード%sの新しいユーザー%sは正常に追加されました';
$hesklang['user_removed']='ユーザーを削除しました';
$hesklang['sel_user_removed']='選択されたユーザがデータベースから正常に削除されました';
$hesklang['profile_for']='プロファイルの対象';
$hesklang['new_pass']='新しいパスワード';
$hesklang['update_profile']='プロフィールの更新';
$hesklang['notify_new_posts']='私のカテゴリ内の新しいチケットと投稿を通知する';
$hesklang['profile_updated']='プロフィールを更新しました';
$hesklang['profile_updated_success']='このプロフィールは正常に更新されました';
$hesklang['view_profile']='プロフィールを見る';
$hesklang['new_ticket_submitted']='新しいサポートチケットが送信されました';
$hesklang['user_profile_updated_success']='このユーザープロファイルは正常に更新されました';
$hesklang['printer_friendly']='プリンターフレンドリーバージョン';
$hesklang['end_ticket']='---チケットの終了 ---';

// CUSTOMER INTERFACE
$hesklang['your_ticket_been']='あなたのチケットは';
$hesklang['submit_ticket']='チケットを送信する';
$hesklang['before_submit']='送信する前に以下を確認してください';
$hesklang['all_info_in']='必要な情報がすべて入力されています';
$hesklang['all_error_free']='すべての情報が正しく、エラーがないこと';
$hesklang['we_have']='私たちは持っています';
$hesklang['recorded_ip']='あなたのIPアドレスとして記録されています';
$hesklang['recorded_time']='投稿した時刻を記録';
$hesklang['save_changes']='変更を保存する';
$hesklang['reply_submitted']='返信が送信されました';
$hesklang['reply_submitted_success']='このチケットへの返信が正常に送信されました';
$hesklang['view_your_ticket']='あなたのチケットを見る';
$hesklang['ticket_submitted']='チケットの送信';
$hesklang['ticket_submitted_success']='チケットは正常に送信されました! チケットID';
$hesklang['your_ticket']='あなたのチケット';


// ADDED IN HESK VERSION 0.94
$hesklang['check_updates']='常に最新バージョンのヘスクをインストールしていることを確認しましょう!';
$hesklang['check4updates']='アップデートをチェックする';
$hesklang['open']='開く';
$hesklang['wait_reply']='返信待ち';
$hesklang['replied']='返信済み';
$hesklang['closed']='解決済'; // チケットは解決済です。
$hesklang['last_replier']='最後の返信者';
$hesklang['staff']='スタッフ';
$hesklang['customer']='顧客';
$hesklang['close_selected']='選択したチケットを解決済みとする';
$hesklang['execute']='実行';
$hesklang['saved_replies']='定型文の回答';
$hesklang['manage_saved']='返信定型文';
$hesklang['manage_intro']='ここでは、返信定型文を追加・管理することができます。これらは、どの顧客に対しても多かれ少なかれ同じような返信をするためによく使われるものです。定型応答を使用することで、異なる顧客に対して何度も同じ回答を入力することを避けることができます。';
$hesklang['no_saved']='定型文のない回答';
$hesklang['delete_saved']='この定型文は本当に削除して良いでしょうか？';
$hesklang['new_saved']='返信定型文の追加・編集';
$hesklang['canned_edit']='選択された定型応答を編集する';
$hesklang['saved_title']='タイトル';
$hesklang['save_reply']='応答を保存する';
$hesklang['saved']='レスポンス保存';
$hesklang['your_saved']='あなたの定型文は、将来の使用のために保存されています。';
$hesklang['ent_saved_title']='返信タイトルを入力してください';
$hesklang['ent_saved_msg']='返信用メッセージを入力してください。';
$hesklang['saved_removed']='定型文は削除されました';
$hesklang['saved_rem_full']='選択された定型文はデータベースから削除されました';
$hesklang['clip_alt']='この投稿には添付ファイルがあります';
$hesklang['attachments']='添付ファイル';
$hesklang['fill_all']='必須項目がありません';
$hesklang['file_too_large']='ファイル %s が大きすぎます。';
$hesklang['created_on']='作成日';
$hesklang['tickets_closed']='Tickets closed';
$hesklang['num_tickets_closed']='<b>%d</b> tickets have been closed';
$hesklang['select_saved']='定型応答を選択する';
$hesklang['select_empty']='選択/空';
$hesklang['insert_special']='特殊タグを挿入（顧客情報に置換されます）';
$hesklang['move_to_catgory']='チケットの移動先';
$hesklang['move']='移動';
$hesklang['moved']='チケットは移動しました';
$hesklang['moved_to']='このチケットは新しいカテゴリに移動しました';
$hesklang['url']='URL';
$hesklang['all_not_closed']='すべて終了しました';
$hesklang['chg_all']='すべてを変更する';
$hesklang['settings']='設定';
$hesklang['settings_intro']='このツールを使って、ヘルプデスクを設定することができます。すべての設定とオプションの詳細については、ヘルプサインをクリックするか、readme.html ファイルを参照してください。';
$hesklang['all_req']='すべての項目（無効なものを除く）が必須です。';
$hesklang['wbst_title']='Webサイトタイトル';
$hesklang['wbst_url']='Webサイト URL';
$hesklang['email_wm']='管理者Email';
$hesklang['max_listings']='1ページあたりの掲載数';
$hesklang['print_size']='印刷時のフォントサイズ';
$hesklang['debug_mode']='デバッグモード';
$hesklang['on']='ON';
$hesklang['off']='OFF';
$hesklang['use_secimg']='reCAPTCHAを利用する';
$hesklang['secimg_no']='使用不可';
$hesklang['attach_use']='アタッチメントを使用する';
$hesklang['attach_num']='投稿ごとの数';
$hesklang['attach_type']='許可されたファイルタイプ';
$hesklang['place_after']='メッセージの後';
$hesklang['place_before']='メッセージの前に';
$hesklang['custom_f']='カスタムフィールド';
$hesklang['custom_u']='このフィールドを使用する';
$hesklang['custom_n']='フィールド名';
$hesklang['custom_l']='最大の長さ';
$hesklang['db_host']='データベースのホスト';
$hesklang['db_name']='データベース名';
$hesklang['db_user']='データベースのユーザー名';
$hesklang['db_pass']='データベースのパスワード';
$hesklang['err_sname']='ウェブサイトのタイトルを入力してください。';
$hesklang['err_surl']='あなたのウェブサイトのURLを入力してください。有効なURLであることを確認してください（http:// または https:// で始まっていること）。';
$hesklang['err_wmmail']='有効なウェブマスターの電子メールを入力してください';
$hesklang['err_nomail']='有効な返信先のEメールを入力してください';
$hesklang['err_htitle']='あなたのサポートデスクのタイトルを入力してください';
$hesklang['err_hurl']='HeskフォルダのURLを入力してください。有効なURLであることを確認してください（http:// または https://で始まります）';
$hesklang['err_lang']='Heskの言語を選択してください';
$hesklang['err_nolang']='言語設定を変更する前に、ファイルがアップロードされていることを確認してください';
$hesklang['err_max']='ページごとに表示される最大リストを入力してください';
$hesklang['err_psize']='印刷のフォントサイズを入力してください。';
$hesklang['err_dbhost']='MySQLデータベースホストを入力してください。';
$hesklang['err_dbname']='MySQLのデータベース名を入力してください';
$hesklang['err_dbuser']='MySQLデータベースのユーザー名を入力してください';
$hesklang['err_dbpass']='MySQLデータベースのパスワードを入力してください';
$hesklang['err_dbsele']='MySQLデータベースを選択できませんでした。データベース名を再確認してください。';
$hesklang['err_openset']='ファイル <b>hesk_settings.inc.php</b> を書き込みのために開くことができません。このファイルを666 (rw-rw-rw-)にCHMODしてください。';
$hesklang ['set_saved'] = '設定が保存されました';
$hesklang ['set_were_saved'] = '設定は正常に保存されました';
$hesklang ['sec_img'] = 'セキュリティイメージ';
$hesklang ['sec_miss'] = 'セキュリティ番号を入力してください';
$hesklang ['sec_wrng'] = '間違ったセキュリティ番号';
$hesklang ['submit_problems'] = '戻って、次の問題を修正してください';
$hesklang ['cat_order'] = 'カテゴリの順序';
$hesklang ['reply_order'] = '定型応答注文';
$hesklang ['move_up'] = '上に移動';
$hesklang ['move_dn'] = '下に移動';
$hesklang ['cat_move_id'] = 'カテゴリIDがありません';
$hesklang ['reply_move_id'] = '既定の応答IDがありません';
$hesklang ['forgot_tid'] = 'トラッキングIDを忘れましたか？';
$hesklang ['tid_send'] = 'トラッキングIDを送ってください';
$hesklang ['tid_not_found'] = 'あなたのメールアドレスのチケットが見つかりませんでした';
$hesklang ['tid_sent'] = '追跡IDが送信されました';
$hesklang ['tid_sent2'] = 'チケットの詳細が記載されたメールがあなたのアドレスに送信されました';
$hesklang ['check_spambox'] = 'SPAM /ジャンクメールボックス内の電子メールも確認してください！';
$hesklang ['reply_not_found'] = '既定の応答が見つかりません';
$hesklang ['exists'] = 'Exists';
$hesklang ['no_exists'] = '存在しません\'存在しません ';
$hesklang ['writable'] = '書き込み可能';
$hesklang ['not_writable'] = '書き込み不可';
$hesklang ['disabled'] = 'disabled';
$hesklang ['e_settings'] = 'このファイルがスクリプトで書き込み可能でない限り、設定を保存することはできません。詳細な手順については、readmeファイルを参照してください！ ';
$hesklang ['e_attdir'] = '添付ファイルフォルダが存在し、スクリプトで書き込み可能でない限り、添付ファイルを使用することはできません。';
$hesklang ['e_save_settings'] = '<b> hesk_settings.inc.php </ b>ファイルはスクリプトで書き込みできないため、設定を保存できません。';
$hesklang ['e_attach'] = '<b> attachments </ b>ディレクトリがスクリプトで書き込み可能ではないため、無効になっています。';
$hesklang ['go'] = 'Go';


// ADDED OR CHANGED IN VERSION 2.0
$hesklang['v']='HESK version';
$hesklang['check_status']='ステータスを確認する';
$hesklang['sub_support']='Submit a ticket';
$hesklang['open_ticket']='新しい問題を部門に送信する';
$hesklang['vet']='過去に送信したチケットを表示する';
$hesklang['enter_user']='ユーザー名を入力してください';
$hesklang['remember_user']='私のユーザー名を覚えておいてください';
$hesklang['wrong_user']='間違ったユーザー名';
$hesklang['no_permission']='このタスクを実行する権限がありません。持っているアカウントでログインしてください。';
$hesklang['tickets_on_pages']='チケットの数:%d |ページ数:%d '; //最初の%dはチケットの数に置き換えられ、2番目の%dはページの数に置き換えられます
$hesklang['jump_page']='|ページにジャンプ: ';
$hesklang['no_tickets_open']='未解決のチケットが見つかりません';
$hesklang['no_tickets_crit']='条件に一致するチケットが見つかりません';
$hesklang['confirm_execute']='続行してもよろしいですか？';
$hesklang['legend']='Legend';
$hesklang['main_page']='ホーム';
$hesklang['menu_users']='ユーザー';
$hesklang['menu_cat']='カテゴリ';
$hesklang['menu_profile']='プロファイル';
$hesklang['menu_kb']='ナレッジベース'; //管理メニュー項目
$hesklang['kb_text']='ナレッジベース'; //顧客に見えるアイテム
$hesklang['viewkb']='ナレッジベース全体を表示';
$hesklang['kb']='ナレッジベースの管理';
$hesklang['kb_intro']='ナレッジベースは、よくある質問（FAQ）に対する回答と、顧客にセルフヘルプリソースを提供する記事のコレクションです。
包括的で適切に記述されたナレッジベースを使用すると、受け取るサポートチケットの数を大幅に減らし、時間を大幅に節約できます。記事をカテゴリに分類できます
およびサブカテゴリ。 '; // ADMINパネルの説明
$hesklang['kb_is']='ナレッジベースは、よくある質問（FAQ）と記事に対する回答の分類されたコレクションです。このカテゴリの記事を読んだり、興味のあるサブカテゴリを選択したりできます。 '; //お客様への説明
$hesklang['new_kb_art']='新しいナレッジベースの記事';
$hesklang['kb_cat']='カテゴリ';
$hesklang['kb_subject']='件名';
$hesklang['kb_content']='コンテンツ';
$hesklang['kb_type']='タイプ';
$hesklang['kb_published']='公開済み';
$hesklang['kb_published2']='記事はナレッジベースのすべてのユーザーが表示できます。';
$hesklang['kb_private']='プライベート';
$hesklang['kb_private2']='私的な記事はスタッフだけが読むことができます。';
$hesklang['kb_draft']='ドラフト';
$hesklang['kb_draft2']='記事は保存されていますが、まだ公開されていません。ナレッジベースの記事を管理する権限を持つ<br/>スタッフのみが読むことができます。 ';
$hesklang['kb_links']='<i> <span class = "notice"> <b>警告!</ b> </ span> <br/>&lt; head&gt;なしで有効なコードを入力してくださいおよび&lt; body&gt;タグ、コンテンツのみ!</ i> ';
$hesklang['kb_ehtml']='これはHTMLコードです（有効な（X）HTMLコードを入力します）';
$hesklang['kb_dhtml']='これはプレーンテキストです（リンクはクリック可能です）';
$hesklang['kb_save']='記事を保存';
$hesklang['kb_e_subj']='記事の件名を入力してください!';
$hesklang['kb_e_cont']='記事の内容を書いてください!';
$hesklang['kb_art_added']='記事が追加されました';
$hesklang['your_kb_added']='新しいナレッジベースの記事が正常に追加されました';
$hesklang['kb_art_deleted']='記事が削除されました';
$hesklang['your_kb_deleted']='選択したナレッジベースの記事は正常に削除されました';
$hesklang['kb_art_mod']='記事が変更されました';
$hesklang['your_kb_mod']='選択した記事への変更は正常に保存されました';
$hesklang['kb_cat_new']='新しいナレッジベースカテゴリ';
$hesklang['kb_cat_parent']='親カテゴリ';
$hesklang['kb_cat_sub']='サブカテゴリ';
$hesklang['kb_cat_title']='カテゴリタイトル';
$hesklang['kb_cat_published']='カテゴリはナレッジベースのすべてのユーザーが表示できます。';
$hesklang['kb_cat_private']='カテゴリはスタッフのみが読み取ることができます。';
$hesklang['kb_cat_add']='カテゴリを追加';
$hesklang['kb_cat_e_title']='カテゴリタイトルを入力してください!';
$hesklang['kb_cat_added']='カテゴリが追加されました';
$hesklang['kb_cat_added2']='新しいカテゴリがナレッジベースに正常に追加されました';
$hesklang['kb_cat_man']='ナレッジベースカテゴリの管理';
$hesklang['kb_cat_edit']='カテゴリの詳細を編集';
$hesklang['kb_cat_inv']='無効なカテゴリ';
$hesklang['kb_cat_art']='このカテゴリの記事';
$hesklang['kb_p_art']='+記事';
$hesklang['kb_p_art2']='選択したカテゴリに新しい記事を追加します。';
$hesklang['kb_add_art']='記事を追加';
$hesklang['kb_p_cat']='+カテゴリ';
$hesklang['kb_p_cat2']='選択したカテゴリ内に新しいサブカテゴリを作成します。';
$hesklang['kb_add_cat']='カテゴリの追加';
$hesklang['kb_p_man']='管理';
$hesklang['kb_p_man2']='選択したカテゴリの管理（記事の編集、削除、管理）';
$hesklang['kb_main']='メインナレッジベースカテゴリは削除または移動できません。';
$hesklang['kb_no_art']='このカテゴリには記事がありません。';
$hesklang['author']='Author';
$hesklang['views']='ビュー';
$hesklang['delete']='削除';
$hesklang['rating']='評価';
$hesklang['votes']='Votes';
$hesklang['kb_rated']='記事の評価は%s / 5.0';
$hesklang['kb_not_rated']='記事はまだ評価されていません';
$hesklang['del_art']='選択した記事を削除してもよろしいですか？';
$hesklang['kb_art_id']='記事IDがないか無効です!';
$hesklang['kb_art_edit']='記事を編集';
$hesklang['revhist']='改訂履歴';
$hesklang['kb_order']='注文';
$hesklang['kb_delcat']='このカテゴリを削除してもよろしいですか？';
$hesklang['kb_cat_mod']='カテゴリが変更されました';
$hesklang['your_cat_mod']='選択したカテゴリへの変更は正常に保存されました';
$hesklang['kb_cat_del']='ナレッジベースカテゴリが削除されました';
$hesklang['kb_cat_dlt']='選択したナレッジベースカテゴリが削除されました。';
$hesklang['allowed_cat']='カテゴリ';
$hesklang['allow_feat']='機能';
$hesklang['can_view_tickets']='チケットを表示';
$hesklang['can_reply_tickets']='チケットに返信';
$hesklang['can_assign_tickets']='チケットの割り当て';
$hesklang['can_del_tickets']='チケットを削除';
$hesklang['can_edit_tickets']='チケットの返信を編集する';
$hesklang['can_man_kb']='ナレッジベースの管理';
$hesklang['can_man_users']='ユーザーの管理';
$hesklang['can_man_cat']='カテゴリの管理';
$hesklang['can_man_canned']='定型応答の管理';
$hesklang['can_man_settings']='ヘルプデスク設定の管理';
$hesklang['can_del_notes']='チケットのメモを削除する';
$hesklang['dan']='ユーザーは自分のチケットメモを削除できます。このユーザーが他のユーザーからもメモを削除できるようにする場合にのみ、これを選択してください';
$hesklang['in_all_cat']='許可されたカテゴリのみ';
$hesklang['admin_can']='（すべての機能とカテゴリへのアクセス）';
$hesklang['staff_can']='（機能とカテゴリを制限できます）';
$hesklang['asign_one_feat']='このユーザーに少なくとも1つの機能を割り当ててください!';
$hesklang['na_view_tickets']='チケットを表示する権限がありません';
$hesklang['support_notice']='申し訳ありませんが、このセクションはHESKライセンスを購入した場合にのみ非表示にできます!';
$hesklang['rart']='この記事は役に立ちましたか？';
$hesklang['r']='この返信は役に立ちましたか？';
$hesklang['tyr']='評価ありがとうございます';
$hesklang['cw']='ウィンドウを閉じる';
$hesklang['cw2']='ウィンドウを閉じてチケットを送信する';
$hesklang['rh']='<i>役に立った</ i>と評価されました';
$hesklang['rnh']='<i>役に立たなかった</ i>と評価されました';
$hesklang['ar']='すでに評価されています';
$hesklang['rated']='ユーザー評価%s / 5.0（%s投票）';
$hesklang['not_rated']='ユーザーはまだ評価されていません';
$hesklang['rdis']='評価が無効になっています';
$hesklang['kbdis']='ナレッジベースが無効になっています';
$hesklang['kbpart']='申し訳ありませんが、この記事にアクセスする権限がありません';
$hesklang['m']='その他のトピック';
$hesklang['noa']='まだ記事はありません';
$hesklang['noac']='このカテゴリにはまだ記事がありません';
$hesklang['dta']='追加日';
$hesklang['aid']='記事ID';
$hesklang['as']='ソリューション';
$hesklang['search']='検索';
$hesklang['nosr']='一致する記事が見つかりません。ナレッジベースを参照するか、新しいサポートチケットを送信してみてください。 ';
$hesklang['rv']='ビューをリセット';
$hesklang['rr']='投票をリセット（評価）';
$hesklang['opt']='オプション';
$hesklang['delcat']='カテゴリの削除';
$hesklang['move1']='記事を親カテゴリに移動';
$hesklang['move2']='このカテゴリの記事を削除する';
$hesklang['sc']='推奨されるナレッジベースの記事';
$hesklang['not']='チケット'; //カテゴリ内のすべてのチケットの数
$hesklang['graph']='グラフ';
$hesklang['lu']='ユーザー名の一覧表示';
$hesklang['aclose']='チケットの自動クローズ';
$hesklang['aclose2']='最後のスタッフの返信から数日後';
$hesklang['s_ucrt']='チケットを再開する';
$hesklang['urate']='返信評価';
$hesklang['hesk_url']='ヘルプデスクのURL';
$hesklang['hesk_title']='ヘルプデスクのタイトル';
$hesklang['cid']='ケース追跡ID';
$hesklang['tfor']='時間形式';
$hesklang['prefix']='テーブルプレフィックス';
$hesklang['s_kbs']='KB検索を有効にする';
$hesklang['s_kbr']='KB評価を有効にする';
$hesklang['s_maxsr']='最大で表示する検索結果数';
$hesklang['s_suggest']='KB記事を提案する';
$hesklang['s_spop']='人気のある記事を表示する';
$hesklang['s_slat']='最新の記事を表示する';
$hesklang['s_onin']='<ahref = "../" target = "_ blank">ヘルプデスクインデックス</a>ページ';
$hesklang['s_onkb']='<ahref = "../ knowledgebase.php" target = "_ blank">ナレッジベースインデックス</a>ページ';
$hesklang['s_scol']='行のカテゴリ';
$hesklang['s_ptxt']='記事のプレビューの長さ';
$hesklang['s_psubart']='サブカテゴリの記事';
$hesklang['enable']='Enable';
$hesklang['s_type']='タイプ';
$hesklang['custom_r']='必須';
$hesklang['custom_place']='場所';
$hesklang['custom_use']='カスタムフィールド';
$hesklang['stf']='テキストフィールド';
$hesklang['stb']='大きなテキストボックス';
$hesklang['srb']='ラジオボタン';
$hesklang['ssb']='選択ボックス';
$hesklang['db']='データベース';
$hesklang['hd']='ヘルプデスク設定';
$hesklang['gs']='一般設定';
$hesklang['cwin']='ウィンドウを閉じる';
$hesklang['defw']='デフォルト値';
$hesklang['ok']='OK';
$hesklang['ns']='これらは、このカスタムフィールドで使用可能なオプションです。変更を保存するには、管理者設定ページの<b> [OK] </ b>と[<b>変更を保存</ b>]ボタンをクリックします! ';
$hesklang['rows']='行（高さ）';
$hesklang['cols']='列（幅）';
$hesklang['opt2']='このラジオボタンのオプション。1行に1つのオプションを入力します（各行は、選択できる新しいラジオボタンの値を作成します）。少なくとも2つのオプションを入力する必要があります! ';
$hesklang['opt3']='この選択ボックスのオプション。1行に1つのオプションを入力します（各行は顧客が選択できる選択肢になります）。少なくとも2つのオプションを入力する必要があります! ';
$hesklang['atl2']='少なくとも2つのオプションを入力してください（1行に1つ）!';
$hesklang['notes']='Notes';
$hesklang['noteby']='Note by';
$hesklang['delnote']='メモを削除';
$hesklang['noteerr']='すでに削除されたか間違ったパラメータに注意してください';
$hesklang['s']='送信';
$hesklang['nhid']='メモは顧客から隠されています!';
$hesklang['delt']='この投稿を削除';
$hesklang['edtt']='投稿の編集';
$hesklang['edt1']='投稿変更';
$hesklang['edt2']='選択した投稿への変更が保存されました';
$hesklang['dele']='このチケットを削除する';
$hesklang['repd']='投稿が削除されました';
$hesklang['repl']='選択した投稿が削除されました';
$hesklang['tickets_found']='検索結果';
$hesklang['al']='管理者リンク';
$hesklang['ap']='管理パネルに移動';
$hesklang['dap']='<ahref = "../" target = "_ blank">ヘルプデスクインデックス</a>からの管理パネルへのリンクを表示します';
$hesklang['q_miss']='スパム対策の質問に答えてください';
$hesklang['use_q']='スパム対策の質問を使用する';
$hesklang['err_qask']='スパム対策の質問を入力してください';
$hesklang['err_qans']='スパム対策の質問に対する回答を入力してください';
$hesklang['genq']='ランダムな質問を生成します';


// Added or modified in version 2.1
$hesklang['amo']='さらに追加';
$hesklang['delatt']='選択した添付ファイルを削除しますか？';
$hesklang['kb_att_rem']='選択した添付ファイルが削除されました';
$hesklang['inv_att_id']='無効な添付ファイルID!';
$hesklang['scb']='チェックボックス';
$hesklang['autologin']='訪問するたびに自動的にログオンします';
$hesklang['just_user']='私のユーザー名だけを覚えておいてください';
$hesklang['nothx']='いいえ覚えなくて大丈夫です';
$hesklang['pinfo']='プロファイル情報';
$hesklang['sig']='署名';
$hesklang['pref']='設定';
$hesklang['aftrep']='チケットに返信した後';
$hesklang['showtic']='返信したばかりのチケットを表示する';
$hesklang['gomain']='メイン管理ページに戻る';
$hesklang['shownext']='返信が必要な次のチケットを開く';
$hesklang['rssn']='注意が必要な次のチケットを表示しています';
$hesklang['mrep']='メッセージを置換';
$hesklang['madd']='一番下に追加';
$hesklang['priv']='スタッフのみが表示できるプライベートカテゴリと記事は*でマークされています';
$hesklang['inve']='無効な電子メールファイル';
$hesklang['emfm']='メールファイルがありません';
$hesklang['hesk_lang']='デフォルト言語';
$hesklang['s_mlang']='複数の言語';
$hesklang['s_mlange']='インストールされているすべての言語でサポートを提供する場合にのみ有効にしてください!';
$hesklang['s_inl']='テスト言語のフォルダー';
$hesklang['ta']='再度テスト';
$hesklang['alo']='自動ログインを許可する';
$hesklang['chol']='優先言語';
$hesklang['mmdl']='これを私の好みの言語にする';
$hesklang['warn']='ダウンロード';
$hesklang['dmod']='デバッグモードが有効になっています。 HESKがインストールされ、正しく機能したら、設定でデバッグモードを無効にしてください。 ';
$hesklang['kb_spar']='カテゴリは\'独自の親カテゴリにすることはできません! ';
$hesklang['mysql_root']='MySQLパスワードが空です。rootユーザーでログインしてもよろしいですか？これは重大なセキュリティリスクです! ';
$hesklang['chg']='変更';
$hesklang['chpri']='優先度が変更されました';
$hesklang['chpri2']='チケット\の優先度が%sに変更されました';
$hesklang['selcan']='編集する定型応答を選択します';
$hesklang['q_wrng']='間違ったスパム対策回答';
$hesklang['cndupl']='あなたはすでにその名前のカテゴリを持っています。カテゴリごとに一意の名前を選択してください。 ';
$hesklang['wsel']='検索するフィールドを選択します';


// Added or modified in version 2.2
$hesklang['eto']='無効なリクエスト';
$hesklang['id']='ID';
$hesklang['geco']='ダイレクトリンクの生成';
$hesklang['genl2']='Use this link to preselect category in the &quot;Submit a ticket&quot; form.';
$hesklang['exa']='例';
$hesklang['small']='Small Box';
$hesklang['large']='Large Box';
$hesklang['cpri']='Customer priority';
$hesklang['owner']='オーナー';
$hesklang['unas']='Unassigned';
$hesklang['assi']='アサイン';
$hesklang['asst']='担当する';
$hesklang ['asst2'] = 'このチケットを';
$hesklang ['asss'] = '自分に割り当てる';
$hesklang ['asss2'] = 'このチケットを自分に割り当てます';
$hesklang ['can_assign_self'] = 'チケットを自分自身に割り当てることができます';
$hesklang ['can_assign_others'] = '他の人にチケットを割り当てることができます';
$hesklang ['can_view_ass_others'] = '他の人に割り当てられたチケットを表示できます';
$hesklang ['unoa'] = '選択したユーザーはこのカテゴリにアクセスできません';
$hesklang ['tasi'] = '所有者が割り当てられました';
$hesklang ['tasy'] = 'このチケットはあなたに割り当てられています';
$hesklang ['taso'] = 'このチケットは選択したユーザーに割り当てられています';
$hesklang['tasy2']='担当';
$hesklang['taso2']='他のスタッフへ割り当て';
$hesklang ['nose'] = '新しい所有者を選択';
$hesklang ['onasc'] = 'この所有者は、選択したカテゴリにアクセスできません。';
$hesklang ['tunasi'] = 'チケットが割り当てられていません';
$hesklang ['tunasi2'] = 'チケットには所有者がいないため、再度割り当てる準備ができています';
$hesklang ['note'] = 'Note';
$hesklang ['success'] = '成功';
$hesklang ['nyt'] = 'このチケットはに割り当てられています';
$hesklang ['noch'] = '変更は行われていません';
$hesklang ['orch'] = '表示順序が変更されました';
$hesklang ['rfm'] = '必要な情報がありません:';
$hesklang ['repl0'] = 'このタスクを実行するには権限が不十分です';
$hesklang ['repl1'] = 'この投稿は存在しません';
$hesklang ['reports'] = 'レポート';
$hesklang ['reports_intro'] = 'レポートセクションでは、複数のレポートを実行して、選択した日付範囲のチケット統計を確認できます。';
$hesklang ['refi'] = 'フォームデータをリセット';
$hesklang ['dich'] = '変更を破棄';
$hesklang['dire']='表示レポート';
$hesklang['m1']='1月';
$hesklang['m2']='2月';
$hesklang['m3']='3月';
$hesklang['m4']='4月';
$hesklang['m5']='5月';
$hesklang['m6']='6月';
$hesklang['m7']='7月';
$hesklang['m8']='8月';
$hesklang['m9']='9月';
$hesklang['m10']='10月';
$hesklang['m11']='11月';
$hesklang['m12']='12月';
$hesklang['d1']='月曜日';
$hesklang['d2']='火曜日';
$hesklang['d3']='水曜日';
$hesklang['d4']='木曜日';
$hesklang['d5']='金曜日';
$hesklang['d6']='土曜日';
$hesklang['d0']='日曜日';
$hesklang['mo']='月曜';
$hesklang['tu']='火曜';
$hesklang['we']='水曜';
$hesklang['th']='木曜';
$hesklang['fr']='金曜';
$hesklang['sa']='土曜';
$hesklang['su']='日曜';
$hesklang['from']='From';
$hesklang['cinv']='無効な日付';
$hesklang['cinv2']='使用可能なフォーマットは mm/dd/yyyy です。';
$hesklang['cinm']='Invalid month value';
$hesklang['cinm2']='Allowed range is';
$hesklang['cind']='Invalid day of month value';
$hesklang['cind2']='Allowed range for selected month is';
$hesklang['month']='月';
$hesklang['ocal']='カレンダーを開く';
$hesklang['ca01']='前年度';
$hesklang['ca02']='前月';
$hesklang['ca03']='来月';
$hesklang['ca04']='次の年';
$hesklang['ca05']='カレンダーを閉じる';
$hesklang['cdr']='日付の範囲を選択します。';
$hesklang['r1']='今日';
$hesklang['r2']='昨日';
$hesklang['r3']='今月';
$hesklang['r4']='先月';
$hesklang['r5']='過去30日';
$hesklang['r6']='今週(月～日)';
$hesklang['r7']='先週(月～日)';
$hesklang['r8']='今週の営業日（月～金）';
$hesklang['r9']='先週の営業日（月～金）';
$hesklang['r10']='今年度';
$hesklang['r11']='昨年度';
$hesklang['r12']='すべての期間';
$hesklang['datetofrom']='&quot;Date From&quot; cannot be higher than &quot;Date to&quot;. The dates have been switched.';
$hesklang['t1']='1日あたりのチケット数';
$hesklang['t2']='1ヶ月あたりのチケット数';
$hesklang['t3']='1ユーザーあたりのチケット数';
$hesklang['t4']='Tickets per category';
$hesklang['ticass']='Assigned tickets';
$hesklang['ticall']='Replied to tickets';
$hesklang['totals']='Totals';
$hesklang['all']='すべて';
$hesklang['atik']='新しいチケット';
$hesklang['kbca']='この名前の知識ベース・カテゴリがすでにあります。';
$hesklang['menu_msg']='メール';
$hesklang['menu_can']='Canned';
$hesklang['m_re']='Re:'; // Mail reply subject prefix, like "Re: Original subject"
$hesklang['m_fwd']='Fwd:'; // Mail forward subject prefix, like "Fwd: Original subject"
$hesklang['m_h']='プライベートメッセージ';
$hesklang['m_intro']='Use private messages to send quick messages to other staff members within the HESK.';
$hesklang['e_udel']='(User deleted)';
$hesklang['new_mail']='新しいプライベートメッセージ';
$hesklang['m_send']='メッセージを送信する';
$hesklang['m_rec']='メッセージの受信者を選択する';
$hesklang['m_inr']='メッセージの受信者が無効';
$hesklang['m_esu']='プライベートメッセージの件名を入力してください';
$hesklang['m_pms']='プライベートメッセージが送信されました';
$hesklang['pg']='ページを見る';
$hesklang['npm']='No private messages in this folder.';
$hesklang['m_ena']='このメッセージを閲覧する権限がありません。';
$hesklang['mau']='未読としてマークする';
$hesklang['mo1']='選択したメッセージを既読にする';
$hesklang['mo2']='選択したメッセージを未読としてマーク';
$hesklang['mo3']='選択したメッセージを削除する';
$hesklang['delm']='このメッセージを削除する';
$hesklang['e_tid']='ユニークなチケットIDの生成に失敗しました。後でもう一度送信してください。';
$hesklang['smmr']='選択されたメッセージは既読になりました';
$hesklang['smmu']='選択されたメッセージは未読としてマークされています';
$hesklang['smdl']='選択されたメッセージは削除されました';
$hesklang['show']='見る';
$hesklang['s_my']='Assigned to me';
$hesklang['s_ot']='Assigned to others';
$hesklang['s_un']='Unassigned tickets';
$hesklang['s_for']='検索する';
$hesklang['s_in']='検索条件';
$hesklang['s_incl']='Search within';
$hesklang['find_ticket_by']='チケットを探す';
$hesklang['e_nose']='No assignment status selected, showing all tickets.';
$hesklang['fsq']='Enter your search query';
$hesklang['topen']='Open'; // Not-resolved tickets
$hesklang['nms']='No messages selected, nothing to change';
$hesklang['tlo']='Lock ticket';
$hesklang['tul']='チケットをアンロックする';
$hesklang['loc']='ロックする';
$hesklang['isloc']='Customers cannot reply to or re-open locked tickets. When locked ticket is marked as resolved.';
$hesklang['tlock']='チケットはロックされています';
$hesklang['tunlock']='チケットのロックが解除されました';
$hesklang['tislock']='This ticket has been locked, the customer will not be able to post a reply.';
$hesklang['tislock2']='This ticket has been locked, you cannot post a reply.';
$hesklang['nsfo']='No relevant articles found.';
$hesklang['elocked']='This ticket has been locked or deleted.';
$hesklang['nti2']='新規チケットの挿入';
$hesklang['nti3']='Use this form to create a new ticket in a customer\'s name. Enter <i>customer</i> information in the form (customer name, customer email, ...) and NOT your name! Ticket will be created as if the customer submitted it.';
$hesklang['addop']='オプション';
$hesklang['seno']='お客様へのお知らせメール送信';
$hesklang['otas']='提出後のチケットの表示';
$hesklang['notn']='お知らせ';
$hesklang['nomw']='ヘルプデスクは、以下の場合にメールで通知します。';
$hesklang['nwts']='A new ticket is submitted with owner:';
$hesklang['ncrt']='Client responds to a ticket with owner:';
$hesklang['ntam']='A ticket is assigned to me';
$hesklang['npms']='A private message is sent to me';
$hesklang['support_remove']='HESKの開発には、多くの時間と労力が費やされました。ヘルプデスク・ソフトウェアHESKによるクレジット・リンクを削除するライセンスを購入することで、HESKをサポートしてください。';
$hesklang['ycvtao']='他の人に割り当てられたチケットを見ることはできません。';
$hesklang['password_not_valid']='パスワードは5文字以上でなければなりません';
$hesklang['lkbs']='ナレッジベースの提案を読み込んでいます...';
$hesklang['auto']='(automatically)';

// Added or modified in version 2.3
$hesklang['unknown']='不明';
$hesklang['pcer']='次のエラーを修正してください:';
$hesklang['seqid']='チケット番号';
$hesklang['close_action']='解決済みとしてマーク'; // ACTIONを閉じます
$hesklang['archived']='タグ付き';
$hesklang['archived2']='タグ付きチケット';
$hesklang['add_archive']='このチケットにタグを付ける';
$hesklang['add_archive_quick']='選択したチケットにタグを付ける';
$hesklang['remove_archive']='このチケットのタグを解除する';
$hesklang['remove_archive_quick']='選択したチケットのタグを解除する';
$hesklang['added_archive']='チケットタグ付き';
$hesklang['removed_archive']='チケットタグなし';
$hesklang['added2archive']='チケットはタグ付けされています';
$hesklang['removedfromarchive']='チケットはタグ付けされていません';
$hesklang['num_tickets_tag']='<b>%d </ b>チケットにタグが付けられました';
$hesklang['num_tickets_untag']='<b>%d </ b>チケットはタグ付けされていません';
$hesklang['can_add_archive']='チケットにタグを付けることができます';
$hesklang['disp_only_archived']='タグ付きチケットのみ';
$hesklang['search_only_archived']='タグ付きチケットのみ';
// START abbreviatons used in "last updated" column
$hesklang['abbr']['year']='y';
$hesklang['abbr']['month']='mo';
$hesklang['abbr']['week']='w';
$hesklang['abbr']['day']='d';
$hesklang['abbr']['hour']='h';
$hesklang['abbr']['minute']='m';
$hesklang['abbr']['second']='s';
// END abberviations
$hesklang['cnsm']='メッセージを次の宛先に送信しません:';
$hesklang['yhbb']='ログインの失敗が多すぎるため、%s分間システムがロックアウトされました。';
$hesklang['pwdst']='パスワード強度';
$hesklang['tid_mail']='心配ありません! <b>メールアドレス</ b>を入力すると、すぐにトラッキングIDが送信されます: ';
$hesklang['rem_email']='私のメールアドレスを覚えておいてください';
$hesklang['eytid']='チケット追跡IDを入力してください。';
$hesklang['enmdb']='入力したメールアドレスが、このチケットIDのデータベース内のメールアドレスと一致しません。';
$hesklang['confemail']='メールの確認';
$hesklang['confemail2']= 'メールアドレスを確認してください';
$hesklang['confemaile']= '2つのメールアドレスは同一ではありません';
$hesklang['taso3']='割り当て先:';
$hesklang['sec_enter']='下の図に表示されている番号を入力してください。';
$hesklang['reload']='画像の再読み込み';
$hesklang['verify_q']='スパム防止:'; //スパム対策の質問の場合
$hesklang['verify_i']='スパム防止:'; //スパム対策イメージ（キャプチャ）の場合
$hesklang['vrfy']= 'テストに合格しました';
$hesklang['last_update']= '更新済み';
$hesklang['cot']='クリティカルチケットを強制しないでください';
$hesklang['def']='これをデフォルトのビューにします';
$hesklang['gbou']='これらのチケットは<b>未割り当て</ b>です:';
$hesklang['gbom']='<b> me </ b>に割り当てられたチケット:';
$hesklang['gboo']='<b>%s </ b>に割り当てられたチケット:';
$hesklang['select']='---クリックして選択---';
$hesklang['chngstatus']= 'ステータスを変更';
$hesklang['perat']= 'すべてのチケットの%s'; //「すべてのチケットの23%」に変更されます
$hesklang['viewart']= 'この記事を表示';
$hesklang['chdp']= '<ahref = "profile.php">プロファイル</a>ページのデフォルトのパスワードを変更してください!';
$hesklang['chdp2']= 'パスワードを変更します。デフォルトのパスワードを使用しています!';
$hesklang['security']='セキュリティ';
$hesklang['kb_i_art']='新しい記事';
$hesklang['kb_i_art2']='記事を挿入';
$hesklang['kb_i_cat']='新しいカテゴリ';
$hesklang['kb_i_cat2']='カテゴリを挿入';
$hesklang['gopr']='ナレッジベースの表示';
$hesklang['kbstruct']='ナレッジベース構造';
$hesklang['cancel']='キャンセル';
$hesklang['sh']='メッセージを非表示';
$hesklang['goodkb']='優れたナレッジベースの記事を書く方法は？';
$hesklang['catset']='カテゴリ設定';
$hesklang['inpr']='新しい優先度を選択';
$hesklang['incat']='新しいカテゴリを選択';
$hesklang['instat']='新しいステータスを選択';
$hesklang['tsst']='チケットステータスは%sに設定されています';
$hesklang['aass']='自動割り当て';
$hesklang['aaon']='チケットの自動割り当てが有効になっています（クリックして無効にします）';
$hesklang['aaoff']='チケットの自動割り当てが無効になっています（クリックして有効にします）';
$hesklang['uaaon']='選択したユーザーに対して自動割り当てが有効になっています';
$hesklang['uaaoff']='選択したユーザーの自動割り当てが無効になっています';
$hesklang['taasy']='このチケットは自動的に割り当てられました';
$hesklang['can_view_unassigned']='割り当てられていないチケットを表示できます';
$hesklang['ycovtay']='自分に割り当てられたチケットのみを表示できます';
$hesklang['in_progress']='進行中';
$hesklang['on_hold']='保留中';
$hesklang['import_kb']='このチケットをナレッジベースの記事にインポートします';
$hesklang['import']='<i>プライベートチケット</ i>を<i>パブリック記事</ i>にインポートしています。<br/> <br/>プライベートまたは機密情報を削除してください記事の件名とメッセージからの情報! ';
$hesklang['tab_1']='一般';
$hesklang['tab_2']='ヘルプデスク';
$hesklang['tab_3']='ナレッジベース';
$hesklang['tab_5']='その他';
$hesklang['disable']='Disable';
$hesklang['dat']='日付&amp;時間';
$hesklang['lgs']='言語';
$hesklang['onc']='ON-顧客';
$hesklang['viewvtic']='チケットを表示';
$hesklang['reqetv']='チケットを表示するにはメールが必要です';
$hesklang['banlim']='ログイン試行制限';
$hesklang['banmin']='禁止時間（分）';
$hesklang['subnot']='通知の送信';
$hesklang['subnot2']='チケットを送信する顧客に通知を表示する';
$hesklang['eseqid']='シーケンシャルID';
$hesklang['sconfe']='メールの確認';
$hesklang['saass']='チケットの自動割り当て';
$hesklang['swyse']='WYSIWYGエディター';
$hesklang['hrts']='Rate HESK';
$hesklang['hrts2']='管理パネルでこのスクリプトリンクを評価する';
$hesklang['emlpipe']='Eメール配管';
$hesklang['emlsend2']='メールの配信形式';
$hesklang['phpmail']='PHP Mail';
$hesklang['smtp']='SMTPサーバー';
$hesklang['smtph']='SMTPホスト';
$hesklang['smtpp']='SMTPポート';
$hesklang['smtpu']='SMTPユーザー名';
$hesklang['smtpw']='SMTPパスワード';
$hesklang['smtpt']='SMTPタイムアウト';
$hesklang['other']='その他';
$hesklang['features']='機能';
$hesklang['can_view_online']='オンラインスタッフメンバーを表示できます';
$hesklang['online']='オンライン';
$hesklang['offline']='オフライン';
$hesklang['onlinep']='ユーザーオンライン'; //表示用
$hesklang['sonline']='ユーザーオンライン'; //設定ページ用
$hesklang['sonline2']='オンラインユーザーを表示します。制限（分）: '; //設定ページ用
$hesklang['gb']='Group by';
$hesklang['dg']='グループ化しない';
$hesklang['err_dpi']='データベース%sには、プレフィックス%sが付いたすべてのHESKテーブルが含まれているわけではなく、変更は保存されていません。';
$hesklang['err_dpi2']='テーブルが見つかりません:';
$hesklang['sme']='SMTPエラー';
$hesklang['scl']='SMTP接続ログ';
$hesklang['dnl']='ダウンロード';
$hesklang['dela']='この添付ファイルを削除';
$hesklang['pda']='この添付ファイルを完全に削除しますか？';
$hesklang['mopt']='その他のオプション';
$hesklang['lopt']='オプションが少ない';
$hesklang['meml']='複数のメール';
$hesklang['meml2']='顧客が複数の連絡先メールアドレスを入力できるようにする';


// Added or modified in version 2.4
$hesklang ['catd'] = '（カテゴリが削除されました）';
$hesklang ['noopen'] = 'このメールアドレスのオープンチケットが見つかりません。';
$hesklang ['maxopen'] = '最大オープンチケット（%dの%d）に達しました。新しいチケットを開く前に、既存のチケットが解決されるまでお待ちください。';
$hesklang ['ntnote'] = '誰かが私に割り当てられたチケットにメモを追加します';
$hesklang ['cat_public'] = 'このカテゴリは公開です（クリックして非公開にします）';
$hesklang ['cat_private'] = 'このカテゴリはPRIVATEです（クリックして公開します）';
$hesklang ['cat_aa'] = 'このカテゴリのチケットを自動割り当てします。';
$hesklang ['cat_type'] = 'このカテゴリを非公開にします（スタッフのみが選択できます）。';
$hesklang ['caaon'] = '選択したカテゴリに対して自動割り当てが有効になっています';
$hesklang ['caaoff'] = '選択したカテゴリの自動割り当てが無効になっています';
$hesklang ['cpub'] = 'カテゴリタイプがPUBLICに変更されました';
$hesklang ['cpriv'] = 'カテゴリタイプがPRIVATEに変更されました';
$hesklang ['cpric'] = '顧客はプライベートカテゴリを選択できません。スタッフのみが選択できます!';
$hesklang ['user_aa'] = 'このユーザーにチケットを自動割り当てします。';
$hesklang ['attach_size'] = '最大ファイルサイズ';
$hesklang['B']='B';
$hesklang['kB']='kB';
$hesklang['MB']='MB';
$hesklang['GB']='GB';
$hesklang['bytes']='bytes';
$hesklang['kilobytes']='kilobytes';
$hesklang['megabytes']='megabytes';
$hesklang['gigabytes']='gigabytes';
$hesklang['smtpssl']='SSL Protocol';
$hesklang['smtptls']='TLS Protocol';
$hesklang ['oo'] = '開くのみ';
$hesklang ['ool'] = '「追跡IDを忘れた」の開いているチケットのみを一覧表示します。 Eメール';
$hesklang ['mop'] = '最大オープンチケット';
$hesklang ['rord'] = '返信注文';
$hesklang ['newbot'] = '一番下の最新の返信';
$hesklang ['newtop'] = 'トップの最新の返信';
$hesklang ['ford'] = '返信フォーム';
$hesklang ['formbot'] = 'フォームを下部に表示';
$hesklang ['formtop'] = 'フォームを上部に表示';
$hesklang ['mysqlv'] = 'MySQLバージョン';
$hesklang ['phpv'] = 'PHPバージョン';
$hesklang ['csrt'] = '現在のHESK時間:';
$hesklang ['listp'] = 'プライベート記事を一覧表示する';
$hesklang ['listd'] = '記事の下書きを一覧表示する';
$hesklang ['artp'] = 'プライベート記事';
$hesklang ['artd'] = '記事のドラフト';
$hesklang['kb_no_part']='No private articles in the knowledgebase.';
$hesklang['kb_no_dart']='No article drafts in the knowledgebase.';
$hesklang['attpri']='You don\'t have access to this attachment.';
$hesklang['can_merge_tickets']='Merge tickets';
$hesklang['mer_selected']='Merge selected tickets';
$hesklang['merged']='Selected tickets have been merged into one.';
$hesklang['merge_err']='There was a problem merging tickets:';
$hesklang['merr1']='select at least two tickets.';
$hesklang['merr2']='target ticket not found.';
$hesklang['merr3']='ticket in a category you don\'t have access to.';
$hesklang['tme']='Ticket %s has been merged with this ticket (%s).';
$hesklang['tme1']='Ticket %s has been merged with ticket %s';
$hesklang['tme2']='To access ticket %s enter associated email address.';
$hesklang['eyou']='Use Profile page to edit your settings.';
$hesklang['npea']='You don\'t have permission to edit this user.';
$hesklang['duplicate_user']='User with this username already exists, choose a different username.';
$hesklang['kw']='Keywords';
$hesklang['kw1']='(optional - separate by space, comma or new line)';
$hesklang['type_not_allowed']='Files ending with <b>%s</b> are not accepted (%s)'; // Files ending with .exe are not accepted (test.exe)
$hesklang['unread']='Customer didn\'t read this reply yet.';
$hesklang['sticky']='Make this article &quot;Sticky&quot;';
$hesklang['stickyon']='Change article to &quot;Sticky&quot;';
$hesklang['stickyoff']='Change article to &quot;Normal&quot;';
$hesklang['ason']='Article marked as &quot;Sticky&quot;';
$hesklang['asoff']='Article marked as &quot;Normal&quot;';
$hesklang['ts']='Time worked';
$hesklang['start']='Start / Stop';
$hesklang['reset']='リセット';
$hesklang['save']='Save';
$hesklang['hh']='時間';
$hesklang['mm']='分';
$hesklang['ss']='秒';
$hesklang['twu']='Time worked on ticket has been updated.';
$hesklang['autoss']='Automatically start timer when I open a ticket';
$hesklang['ful']='File upload limits';
$hesklang['ufl']='You may upload files ending with:';
$hesklang['nat']='Maximum number of attachments:';
$hesklang['mfs']='Maximum size per attachment:';
$hesklang['lps']='Your language preference has been saved';
$hesklang['sav']='記事の閲覧数を表示する';
$hesklang['sad']='記事の日付を表示する';
$hesklang['epd']='[HESK] EMAIL PIPING IS DISABLED IN SETTINGS';
$hesklang['pfd']='[HESK] POP3 FETCHING IS DISABLED IN SETTINGS';
$hesklang['pem']='[Piped email]'; // Default subject of piped tickets without subject
$hesklang['pde']='[Customer]'; // Default customer name for piped tickets without name
$hesklang['tab_6']='Email';
$hesklang['pop3']='POP3 Fetching';
$hesklang['pop3h']='POP3 Host';
$hesklang['pop3p']='POP3 Port';
$hesklang['pop3tls']='TLS Protocol';
$hesklang['pop3u']='POP3 Username';
$hesklang['pop3w']='POP3 Password';
$hesklang['pop3e']='POP3 error';
$hesklang['pop3log']='POP3 connection log';
$hesklang['mysqltest']='Test MySQL connection';
$hesklang['smtptest']='Test SMTP connection';
$hesklang['pop3test']='Test POP3 connection';
$hesklang['contest']='Testing connection, this can take a while...';
$hesklang['conok']='Connection successful!';
$hesklang['conokn']='However, if your server requires username and password email will not be sent!';
$hesklang['saving']='Saving settings, please wait...';
$hesklang['sns']='Settings were saved, but some functions were disabled because of failed tests.';
$hesklang['loops']='Email Loops';
$hesklang['looph']='最大ヒット数';
$hesklang['loopt']='Timeframe';
$hesklang['didum']='Did you mean %s?'; // Did you mean someone@gmail.com?
$hesklang['yfix']='Yes, fix it';
$hesklang['nole']='No, leave it';
$hesklang['sconfe2']='チケット送信フォームにquot;Confirm email&quot;フィールドを表示する。';
$hesklang['oln']='Old name:';
$hesklang['nen']='New name:';
$hesklang['use_form_below']='<i>Use this form to submit a support request. Required fields are marked with</i>';
$hesklang['esf']='Could not send email notifications.';
$hesklang['qrr']='(quoted reply removed)';
$hesklang['remqr']='返信を引用したストリップ';
$hesklang['remqr2']='お客様からのメールから引用された返信を削除する';
$hesklang['suge']='メールのタイプミスを防ぐ';
$hesklang['epro']='メールプロバイダ';
$hesklang['email_noreply']='&laquo;送信元:&raquo; メールアドレス';
$hesklang['email_name']='&laquo;送信元:&raquo; 名前';
$hesklang['vscl']='サーバー構成の制限';
$hesklang['fnuscphp']='File upload failed, try with a smaller or no file attachment.';
$hesklang['redv']='reset default view';
$hesklang['fatte1']='Your attachments setting &quot;Number per post&quot; is larger than what your server allows!';
$hesklang['fatte2']='Your maximum attachment file size is larger than what your server allows!';
$hesklang['fatte3']='Your server does not allow large enough posts, try reducing number of attachments or allowed file size!';
$hesklang['embed']='埋め込みファイル';
$hesklang['embed2']='埋め込みファイルを添付ファイルとして使用';
$hesklang['emrem']='(image removed)';
$hesklang['hdemo']='(HIDDEN IN DEMO)';
$hesklang['ddemo']='Sorry, this function has been disabled in DEMO mode!';
$hesklang['sdemo']='Saving changes has been disabled in DEMO mode';
$hesklang['hud']='HESK is up to date';
$hesklang['hnw']='Update available';
$hesklang['getup']='Update HESK';
$hesklang['updates']='アップデート';
$hesklang['updates2']='HESKのアップデートを自動でチェックします。';


// Added or modified in version 2.5.0
$hesklang['emp']='Your PHP does not have MySQL support enabled (mysqli extension required)';
$hesklang['attdel']='This file has been deleted from the server and is no longer available for download';
$hesklang['cannot_move_tmp']='Cannot move file to the attachments folder';
$hesklang['dsen']='Don\'t send email notification of this reply to the customer';
$hesklang['attrem']='* Some attached files have been removed *';
$hesklang['attnum']='Max number reached: %s'; // %s will show attachment name
$hesklang['attsiz']='File too large: %s'; // %s will show attachment name
$hesklang['atttyp']='Type not allowed: %s'; // %s will show attachment name
$hesklang['adf']='管理者フォルダ';
$hesklang['atf']='添付ファイルフォルダ';
$hesklang['err_adf']='The selected admin folder (%s) does not exist!'; // %s will show folder name
$hesklang['err_atf']='The selected attachments folder (%s) does not exist!'; // %s will show folder name
$hesklang['err_atr']='The selected attachments folder (%s) is not writable!'; // %s will show folder name
$hesklang['fatt']='Files attached to this message:';
$hesklang['wrepo']='Please write a reply after re-opening the ticket.';
$hesklang['uac']='Verify and update category article count';
$hesklang['acv']='Article count has been verified';
$hesklang['xyz']='number of public, private and draft articles in category.';
$hesklang['crt']='Report type';
$hesklang['can_run_reports']='Can run reports (own)';
$hesklang['can_run_reports_full']='Can run reports (all)';
$hesklang['can_export']='Can export tickets';
$hesklang['roo']='<i>(only tickets assigned to you are included in the report)</i>';
$hesklang['shu']='ショートリンク';
$hesklang['export_btn']='チケットをエクスポート'; // Button title
$hesklang['export_intro']='This tool allows you to export tickets into an XML spreadsheet that can be opened in Excel.';
$hesklang['stte']='Select tickets to export';
$hesklang['dtrg']='Date range';
$hesklang['sequentially']='Sequentially'; // Order tickets: Sequentially
$hesklang['ede']='Cannot create export directory, please manually create a folder called <b>export</b> inside your attachments folder and make sure it is writable by PHP (on Linux CHMOD it to 777 - rwxrwxrwx).';
$hesklang['eef']='Cannot create export file, no permission to write inside the export directory.';
$hesklang['inite']='Initializing export';
$hesklang['gXML']='Generating XML file';
$hesklang['nrow']='Number of rows exported: %d'; // %d will show number of rows exported
$hesklang['cZIP']='Compressing file into a Zip archive';
$hesklang['eZIP']='Error creating Zip archive';
$hesklang['fZIP']='Finished compressing the file';
$hesklang['pmem']='Peak memory usage: %.2f Mb'; // %.2f will be replaced with number of Mb used
$hesklang['ch2d']='&raquo; CLICK HERE TO DOWNLOAD THE EXPORT FILE &laquo;';
$hesklang['n2ex']='No tickets found matching your criteria, nothing to export!';
$hesklang['sp']='スパム対策'; // For settings page
$hesklang['sis']='Simple image';
$hesklang['pop3keep']='Keep a copy';
$hesklang['err_dbconn']='Could not connect to MySQL database using provided information!';
$hesklang['s_inle']='Testing the language folder for valid languages. Only languages that pass all tests are properly installed.';
$hesklang['ask']='Search help:';
$hesklang['beta']='(TEST VERSION)';
$hesklang['maxpost']='You probably tried to submit more data than this server accepts.<br /><br />Please try submitting the form again with smaller or no attachments.';

// --> Ticket history log
// Unless otherwise specified, first %s will be replaced with date and second with name/username
$hesklang['thist1']='<li class="smaller">%s | moved to category %s by %s</li>'; // %s = date, new category, user making change
$hesklang['thist2']='<li class="smaller">%s | assigned to %s by %s</li>'; // %s = date, assigned user, user making change
$hesklang['thist3']='<li class="smaller">%s | closed by %s</li>';
$hesklang['thist4']='<li class="smaller">%s | opened by %s</li>';
$hesklang['thist5']='<li class="smaller">%s | locked by %s</li>';
$hesklang['thist6']='<li class="smaller">%s | unlocked by %s</li>';
$hesklang['thist7']='<li class="smaller">%s | ticket created by %s</li>';
$hesklang['thist8']='<li class="smaller">%s | priority changed to %s by %s</li>'; // %s = date,new priority, user making change
$hesklang['thist9']='<li class="smaller">%s | status changed to %s by %s</li>'; // %s = date, new status, user making change
$hesklang['thist10']='<li class="smaller">%s | automatically assigned to %s</li>';
$hesklang['thist11']='<li class="smaller">%s | submitted by email piping</li>';
$hesklang['thist12']='<li class="smaller">%s | attachment %s deleted by %s</li>'; // %s = date, deleted attachment, user making change
$hesklang['thist13']='<li class="smaller">%s | merged with ticket %s by %s</li>'; // %s = date, merged ticket ID, user making change
$hesklang['thist14']='<li class="smaller">%s | time worked updated to %s by %s</li>'; // %s = date, new time worked, user making change
$hesklang['thist15']='<li class="smaller">%s | submitted by %s</li>';
$hesklang['thist16']='<li class="smaller">%s | submitted by POP3 fetching</li>';

// --> Knowledgebase articles log
// First %s will be replaced with date and second with user making changes
$hesklang['revision1']='<li class="smaller">%s | submitted by %s</li>';
$hesklang['revision2']='<li class="smaller">%s | modified by %s</li>';


// Added or modified in version 2.5.3
$hesklang['close_this_ticket']='Mark this ticket Resolved';


// Added or modified in version 2.6.0
$hesklang['ms01']='Jan';
$hesklang['ms02']='Feb';
$hesklang['ms03']='Mar';
$hesklang['ms04']='Apr';
$hesklang['ms05']='May';
$hesklang['ms06']='Jun';
$hesklang['ms07']='Jul';
$hesklang['ms08']='Aug';
$hesklang['ms09']='Sep';
$hesklang['ms10']='Oct';
$hesklang['ms11']='Nov';
$hesklang['ms12']='Dec';
$hesklang['sdf']='提出された日付の形式';
$hesklang['lcf']='Updated date format';
$hesklang['lcf0']='ショート ディスクリプション';
$hesklang['lcf1']='日にちと時間';
$hesklang['lcf2']='HESK スタイル';
$hesklang['ticket_tpl']='チケットテンプレート';
$hesklang['can_man_ticket_tpl']='チケットテンプレートを管理する'; // Permission title
$hesklang['ticket_tpl_man']='チケットテンプレートを管理する'; // Page/link title
$hesklang['ticket_tpl_intro']='Create and edit ticket templates that you can use to quickly submit new tickets from the admin interface.';
$hesklang['no_ticket_tpl']='チケットテンプレートはありません';
$hesklang['ticket_tpl_title']='タイトル';
$hesklang['delete_tpl']='Are you sure you want to delete this template?';
$hesklang['new_ticket_tpl']='Add or Edit a ticket template';
$hesklang['ticket_tpl_edit']='Edit selected ticket template';
$hesklang['save_ticket_tpl']='Save ticket template';
$hesklang['ticket_tpl_saved']='Your ticket template has been saved for future use';
$hesklang['ticket_tpl_removed']='Selected ticket template has been removed from the database';
$hesklang['ticket_tpl_not_found']='Ticket template not found';
$hesklang['sel_ticket_tpl']='Select the ticket template you would like to edit';
$hesklang['ent_ticket_tpl_title']='Please enter template title';
$hesklang['ent_ticket_tpl_msg']='Please enter template message';
$hesklang['ticket_tpl_id']='Missing ticket template ID';
$hesklang['select_ticket_tpl']='Select a ticket template';
$hesklang['list_tickets_cat']='List all tickets in this category';
$hesklang['def_msg']='[No message]';
$hesklang['emlreqmsg']='メッセージを要求する';
$hesklang['emlreqmsg2']='メッセージのないパイピング/フェッチされたメールを無視する';
$hesklang['relart']='関連記事'; // Title of related articles box
$hesklang['s_relart']='関連記事'; // On settings page
$hesklang['tab_7']='Ticket list';
$hesklang['fitl']='Fields in ticket list';
$hesklang['submitted']='提出済み';
$hesklang['clickemail']='見る';
$hesklang['set_pri_to']='Set priority to:'; // Action below the ticket list
$hesklang['pri_set_to']='Priority has been set to:';
$hesklang['cat_pri']='The category priority will be used when customers are not allowed to select priority and a ticket is submitted from the customer interface.';
$hesklang['cat_pri_info']='お客様は優先順位を選択することができますので、カテゴリー優先順位は無視されます。<br /><br />カテゴリ優先で使用する場合は、HESKの設定で以下の機能をOFFにしてください。';
$hesklang['def_pri']='Category priority:';
$hesklang['ch_cat_pri']='Set category priority';
$hesklang['cat_pri_ch']='Category priority has been set to:';
$hesklang['err_dbversion']='Too old MySQL version:'; // %s will be replaced with MySQL version
$hesklang['signature_max']='Signature (max 1000 chars)';
$hesklang['signature_long']='User signature is too long! Please limit the signature to 1000 chars';
$hesklang['ip_whois']='IP WHOIS';
$hesklang['ednote']='Edit note message';
$hesklang['ednote2']='Note message saved';
$hesklang['perm_deny']='Permission denied';
$hesklang['mis_note']='Missing note ID';
$hesklang['no_note']='Note with this ID not found';
$hesklang['sacl']='Save and continue later';
$hesklang['reply_saved']='Your reply message has been saved for later.';
$hesklang['submit_as']='Submit as:';
$hesklang['sasc']='Submit as Customer reply';
$hesklang['creb']='Customer reply entered by:';
$hesklang['show_select']='Show &quot;Click to select&quot; as default option';
// Settings
$hesklang['mms']='メンテナンスモード';
$hesklang['mmd']='メンテナンスモードを有効にする';
// Customer notice
$hesklang['mm1']='メンテナンス中';
$hesklang['mm2']='In order to perform scheduled maintenance, our help desk has shut down temporarily.';
$hesklang['mm3']='We apologize for the inconvenience and ask that you please try again later.';
// Staff notice
$hesklang['mma1']='Maintenance mode is active!';
$hesklang['mma2']='Customers are not able to use the help desk.';
$hesklang['tools']='ツール';
$hesklang['banemail_intro']='特定のメールアドレスからヘルプデスクにチケットを送信できないようにします。';
$hesklang['no_banemails']='<i>ブロックされたメールアドレスはありません</i>';
$hesklang['eperm']='Permanent email bans:';
$hesklang['bananemail']='Email address to ban';
$hesklang['savebanemail']='このメールをブロック';
$hesklang['enterbanemail']='Enter the email address you wish to ban.';
$hesklang['validbanemail']='Enter a valid email address (<i>john.doe@example.com</i>) or email domain (<i>@example.com</i>)';
$hesklang['email_banned']='The email address <i>%s</i> was banned and HESK will no longer accept tickets from this address.'; // %s will be replaced with email
$hesklang['emailbanexists']='The email address <i>%s</i> is already banned.'; // %s will be replaced with email
$hesklang['email_unbanned']='Email ban deleted';
$hesklang['banby']='実行したスタッフ';
$hesklang['delban_confirm']='Delete this ban?';
$hesklang['baned_e']='You have been banned from submitting new support tickets.';
$hesklang['baned_ip']='You have been banned from this help desk';
$hesklang['can_ban_emails']='Can ban emails';
$hesklang['can_unban_emails']='Can unban emails (enables Can ban emails)';
$hesklang['eisban']='This email address is banned.';
$hesklang['click_unban']='Click here to unban.';
$hesklang['banip_intro']='禁止されたIPアドレスからの訪問者は、チケットの閲覧や送信、ヘルプデスクへのログインができなくなります。';
$hesklang['ipperm']='ブロックされたIPアドレス:';
$hesklang['iptemp']='Login failure bans:';
$hesklang['savebanip']='IPをブロック';
$hesklang['no_banips']='<i>禁止されているIPはありません</i>';
$hesklang['bananip']='IP address to ban';
$hesklang['banex']='例:';
$hesklang['iprange']='IP range';
$hesklang['ippermban']='Ban this IP permanently';
$hesklang['enterbanip']='Enter the IP address or range you wish to ban.';
$hesklang['validbanip']='Enter a valid IP address or IP range';
$hesklang['ip_banned']='The IP address <i>%s</i> was banned and HESK will no longer accept tickets from this IP address.'; // %s will be replaced with ip
$hesklang['ip_rbanned']='The IP range <i>%s</i> was banned and HESK will no longer accept tickets from this IP range.'; // %s will be replaced with ip
$hesklang['ipbanexists']='The IP address <i>%s</i> is already banned.'; // %s will be replaced with ip
$hesklang['iprbanexists']='The IP range <i>%s</i> is already banned.'; // %s will be replaced with ip
$hesklang['ip_unbanned']='IP ban deleted';
$hesklang['ip_tempun']='Temporary IP ban deleted';
$hesklang['can_ban_ips']='Can ban ips';
$hesklang['can_unban_ips']='Can unban ips (enables Can ban ips)';
$hesklang['ipisban']='This IP address is banned.';
$hesklang['m2e']='Expires in (minutes)';
$hesklang['info']='Info';
$hesklang['sm_intro']='Display a service message in the customer area, for example to notify them about known issues and important news.';
$hesklang['can_service_msg']='Edit service messages';
$hesklang['new_sm']='New service message';
$hesklang['edit_sm']='Edit service message';
$hesklang['ex_sm']='Existing service messages';
$hesklang['sm_author']='Author';
$hesklang['sm_type']='Type';
$hesklang['sm_published']='Published';
$hesklang['sm_draft']='Draft';
$hesklang['sm_style']='スタイル';
$hesklang['sm_none']='None';
$hesklang['sm_success']='Success';
$hesklang['sm_info']='Info';
$hesklang['sm_notice']='Notice';
$hesklang['sm_error']='Error';
$hesklang['sm_mtitle']='Title';
$hesklang['sm_msg']='Message';
$hesklang['sm_e_title']='Enter service message title';
$hesklang['sm_e_msg']='Enter service message';
$hesklang['sm_e_id']='Missing message ID';
$hesklang['sm_added']='A new service message has been added';
$hesklang['sm_deleted']='Service message deleted';
$hesklang['sm_not_found']='This service message does not exist';
$hesklang['no_sm']='サービスメッセージはありません';
$hesklang['del_sm']='Delete this service message?';
$hesklang['sm_mdf']='Service message has been saved';
$hesklang['sska']='Show suggested articles';
$hesklang['taws']='These articles were suggested:';
$hesklang['defaults']='Defaults';
$hesklang['pncn']='Select notify customer option in the new ticket form';
$hesklang['pncr']='Select notify customer option in the ticket reply form';
$hesklang['pssy']='Show what knowledgebase articles were suggested to customers';
$hesklang['ccct']='Customer resolve';
$hesklang['custnot']='お客様にお知らせする時期';
$hesklang['notnew']='新しいサポートチケットが送信されました。';
$hesklang['notclo']='サポートチケットに「解決済み」のマークがつく';
$hesklang['spamn']='スパム通知';
$hesklang['spam_inbox']='<span style="color:red"><b>No confirmation email?</b><br />We sent a confirmation message to your email address. If you do not receive it within a few minutes, please check your Junk, Bulk or Spam folders. Mark the message as <b>Not SPAM</b> to avoid problems receiving our correspondence in the future.</span>';
$hesklang['s_ekb']='ナレッジベースを有効にします';
$hesklang['ekb_n']='<b>NO</b>, ナレッジベースを無効にします';
$hesklang['ekb_y']='<b>YES</b>, ナレッジベースを有効にします';
$hesklang['ekb_o']='<b>YES</b>, ナレッジベースのみを有効にします (<i>ヘルプデスクは無効</i>)';
$hesklang['kb_set']='ナレッジベース設定';
$hesklang['kbo1']='Knowledgebase-only mode';
$hesklang['kbo2']='<br /><br />Visitors cannot submit new support tickets and are taken directly to the knowledgebase.';
$hesklang['fpass']='パスワーをお忘れですか？';
$hesklang['passr']='パスワードをリセット';
$hesklang['passa']='忘れたパスワードを電子メールでリセットできるようにする。';
$hesklang['passe']='メールアドレスを入力してください。';
$hesklang['noace']='そのメールアドレスを持つアカウントは見つかりませんでした';
$hesklang['pemls']='パスワードの再設定方法を記載したメールをお送りしました。';
$hesklang['reset_password']='ヘルプデスクのパスワードをリセットする'; // Email subject
$hesklang['ehash']='無効または期限切れのパスワードリセットリンク';
$hesklang['ehaip']='Wrong IP address. Passwords may only be reset from the IP address that requested password reset.';
$hesklang['resim']='<b>Setup your new password in the form below!</b>';
$hesklang['permissions']='Permissions';
$hesklang['atype']='Account type';
$hesklang['astaff']='スタッフ';
$hesklang['oon1']='Send me only open tickets';
$hesklang['oon2']='Send me all my tickets';
$hesklang['anyown']='Any owner';
$hesklang['pfr']='Another POP3 fetching task is still in progress.';
$hesklang['pjt']='Task timeout';
$hesklang['pjt2']='minutes after start';
$hesklang['nkba']='Knowledgebase search requires enough unique articles to work properly.<br /><br />Consider adding more articles to the knowledgebase to improve search and article suggestion results.';
$hesklang['saa']='Sticky articles are displayed at the top of articles list';
$hesklang['yhbr']='You have been locked out the system for %s minutes because of too many replies to a ticket.';

// Language for Google reCaptcha API version 2
// Supported language codes: https://developers.google.com/recaptcha/docs/language
// If your language is NOT in the supported langauges, leave 'en'
$hesklang['RECAPTCHA']='en';


// Added or modified in version 2.7.0
$hesklang['imap']='IMAP Fetching';
$hesklang['imaph']='IMAP Host';
$hesklang['imapp']='IMAP Port';
$hesklang['enc']='Encryption';
$hesklang['ssl']='SSL';
$hesklang['tls']='TLS';
$hesklang['none']='None';
$hesklang['imapu']='IMAP ユーザー名';
$hesklang['imapw']='IMAP パスワード';
$hesklang ['imaptest'] = 'IMAP接続をテストする';
$hesklang ['ifd'] = '[HESK] IMAPフェッチが設定で無効になっています';
$hesklang ['iei'] = '[HESK] PHPIMAP拡張機能がインストールされていません。';
$hesklang ['ifr'] = '別のIMAPフェッチタスクがまだ進行中です。';
$hesklang ['arp'] = 'ページの自動再読み込み';
$hesklang ['arpp'] = 'チケットリストを含むページを自動的にリロードします:';
$hesklang ['seconds'] = '秒'; // X '秒'ごとにページをリロードします
$hesklang ['minutes'] = '分'; // X分ごとにページをリロードします
$hesklang ['atbr'] = 'このチケットは、返信する前に割り当てる必要があります。';
$hesklang ['attm'] = 'このチケットを私に割り当てます';
$hesklang ['owneed'] = '所有者が必要';
$hesklang ['taat'] = 'このチケットはすでに<b>%s </ b>に割り当てられています。';
$hesklang ['scoy'] = '本当に自分に割り当てますか？';
$hesklang ['scot'] = '本当に%sに割り当てますか？';
$hesklang ['ycto'] = 'はい、所有者を変更します';
$hesklang ['ncto'] = 'いいえ、現在の所有者を保持します';
$hesklang ['fass'] = '所有者が必要';
$hesklang ['req_sub'] = '件名が必要';
$hesklang ['req_msg'] = 'メッセージが必要';
$hesklang ['req_email'] = 'メールが必要';
$hesklang ['default_subject'] = '%sからのチケット'; //デフォルトのチケットの件名、%sは名前に置き換えられます
$hesklang ['off-hide'] = '顧客フォームに非表示';
$hesklang ['ons'] = 'ON-みんな'; //管理者設定ページの場合
$hesklang ['not_valid_email'] = '有効なメールアドレスを入力するか、このフィールドを空のままにします';
$hesklang ['write_down'] = '<spanstyle = "color:red">後で参照できるようにチケットIDを書き留めておくことをお勧めします。</ span>';
$hesklang ['re_confirm1'] = 'これを無効にすると、[セキュリティ]の下の[チケットを表示するために電子メールを要求する]も無効になります。続行？';
$hesklang ['re_confirm2'] = 'これを有効にすると、[機能]の下の[メールが必要]も有効になります。続行？';
$hesklang ['can_email_tpl'] = 'メールテンプレートの編集'; //スタッフの許可
$hesklang ['et_intro'] = 'スタッフと顧客に送信される電子メールを変更します';
$hesklang ['file'] = 'ファイル';
$hesklang ['efile'] = 'ファイルの編集';
$hesklang ['desc_forgot_ticket_id'] = '（顧客）チケット追跡IDを忘れた';
$hesklang ['desc_new_reply_by_staff'] = '（顧客）新しいスタッフの返信';
$hesklang ['desc_new_ticket'] = '（顧客）チケットを受け取りました';
$hesklang ['desc_ticket_closed'] = '（顧客）チケットが閉じられました/解決されました';
$hesklang ['desc_category_moved'] = '（スタッフ）チケットが新しいカテゴリに移動しました';
$hesklang ['desc_new_reply_by_customer'] = '（スタッフ）新しい顧客の返信';
$hesklang ['desc_new_ticket_staff'] = '（スタッフ）新しいチケットが送信されました';
$hesklang ['desc_ticket_assigned_to_you'] = '（スタッフ）チケットがあなたに割り当てられました';
$hesklang ['desc_new_pm'] = '（スタッフ）新しいプライベートメッセージ';
$hesklang ['desc_new_note'] = '（スタッフ）あなたに割り当てられたチケットの新しいメモ';
$hesklang ['desc_reset_password'] = '（スタッフ）パスワードをリセットします';
$hesklang ['et_e_id'] = 'テンプレートIDがありません';
$hesklang ['et_fm'] = 'このメールテンプレートファイルがありません';
$hesklang ['et_fw'] = 'このメールテンプレートファイルは書き込み可能ではありません';
$hesklang ['updated_on'] = '更新日';
$hesklang['ticket_url']='Ticket URL';
$hesklang['pm_url']='Private message URL';
$hesklang['et_num']='Number of tickets';
$hesklang['et_list']='List of support tickets';
$hesklang['et_empty']='Email template cannot be empty';
$hesklang['et_saved']='Email template saved';
$hesklang['source']='Source';
$hesklang['select_category']='Select a category';
$hesklang['select_category_text']='What can we help you with?';
$hesklang['select_category_staff']='Select ticket category';
$hesklang['scat']='Category select limit';
$hesklang['scat2']='(カテゴリ数が多い場合、セレクトボックスが表示されます）';
$hesklang['new_cf']='New custom field';
$hesklang['cf_intro']='Use this feature to add custom fields to the Submit a ticket form so you can collect additional data from customers.';
$hesklang['cf_public']='公開';
$hesklang['cf_private']='Staff only';
$hesklang['cf_cust']='For customers';
$hesklang['cf_all']='All';
$hesklang['cf_cat']='Selected';
$hesklang['cf_ctrl']='Tip: hold down CTRL key to select multiple categories';
$hesklang['visibility']='Visibility';
$hesklang['cf_save']='Save custom field';
$hesklang['ex_cf']='Active custom fields';
$hesklang['no_cf']='No active custom fields';
$hesklang['del_cf']='Delete this custom field? This will also delete any saved custom field data from the database!';
$hesklang['cf_e_id']='Invalid ID';
$hesklang['edit_cf']='Edit custom field';
$hesklang['cf_deleted']='Custom field deleted';
$hesklang['cf_not_found']='This custom field does not exist';
$hesklang['err_custname']='Enter custom field name';
$hesklang['cf_added']='A new custom field has been added';
$hesklang['cf_nocat']='Select at least one category for this custom field';
$hesklang['cf_mdf']='Custom field has been saved';
$hesklang['opt4']='Options for this checkbox, enter one option per line. Each line will be a choice your customers can choose from, multiple choices are possible.';
$hesklang['atl1']='Enter at least one option.';
$hesklang['sch']='Hidden';
$hesklang['meml3']='Allow multiple emails to be entered';
$hesklang['dmin']='Minimum accepted date';
$hesklang['dmax']='Maximum accepted date';
$hesklang['d_day']='day(s)';
$hesklang['d_week']='week(s)';
$hesklang['d_month']='month(s)';
$hesklang['d_year']='year(s)';
$hesklang['d_any']='Any date';
$hesklang['d_fixed']='Fixed date';
$hesklang['d_relative']='Relative date';
$hesklang['d_mm']='Minimum date may not be higher than maximum date';
$hesklang['d_emin']='Minimum date for <i>%s</i> is %s'; // Minimum date for FIELD_NAME is DATE
$hesklang['d_emax']='Maximum date for <i>%s</i> is %s'; // Maximum date for FIELD_NAME is DATE
$hesklang['d_format']='Date display format';
$hesklang['d_custom']='Custom format';
$hesklang['d_ci']='ADVANCED USERS ONLY: a valid PHP date format, see PHP manual.';
$hesklang['cf_noe']='Enter a valid email address into <i>%s</i>';
$hesklang['cf_noem']='Enter one or more valid email addresses into <i>%s</i>';
$hesklang['cf_limit']='You have 50 active custom fields, no new can be created.';
$hesklang['can_resolve']='Can resolve tickets';
$hesklang['can_change_cat']='Change ticket category (to any)';
$hesklang['can_change_own_cat']='Change ticket category (to allowed)';
$hesklang['can_submit_any_cat']='Can submit tickets to any category';
$hesklang['noauth_submit']='You are not authorized to submit tickets to this category!';
$hesklang['noauth_move']='You are not authorized to move tickets to this category!';
$hesklang['noauth_resolve']='You are not authorized to resolve tickets!';
$hesklang['force_ssl']='SSL接続の強制';
$hesklang['d_ssl']='<i>disabled</i> - open this page with https:// to manage this option';
$hesklang['enn']='ただし、メールの件名にチケットが含まれている場合は、メールからのチケットは除く。';
$hesklang['scno']='This status cannot be changed';
$hesklang['statuses']='ステータス';
$hesklang['statuses_intro']='Use this tool to add custom ticket statuses to your help desk';
$hesklang['color']='カラー';
$hesklang['csscl']='CSSのクラスまたはカラー';
$hesklang['clr_view']='Color preview on text';
$hesklang['cbc']='お客様によるカスタマイズ';
$hesklang['ccc']='Can customers change this status?';
$hesklang['del_status']='Delete this status?';
$hesklang['ex_status']='Existing statuses';
$hesklang['status_hesk']='内蔵のステータス（ここでは変更不可）';
$hesklang['status_custom']='Custom Statuses';
$hesklang['list_tkt_status']='List all tickets with this status';
$hesklang['new_status']='新しいカスタムステータス';
$hesklang['edit_status']='Edit custom status';
$hesklang['err_status']='Enter the status name';
$hesklang['status_added']='A new custom status has been added';
$hesklang['status_e_id']='Invalid ID';
$hesklang['status_mdf']='Custom status has been saved';
$hesklang['status_deleted']='Custom status deleted';
$hesklang['status_not_found']='This custom status does not exist';
$hesklang['status_not_empty']='This status cannot be removed because tickets with this status exist';
$hesklang['status_limit']='You have 100 custom statuses, no new can be created.';
$hesklang['public_link']='Public link'; // Link to the public KB article in the private KB pages
$hesklang['frames']='フレーム';
$hesklang['frames2']='サードパーティードメインでフレーム内にHESKを読み込まないようにする。';
$hesklang['numsub']='Submitted tickets'; // Will show how many tickets this user submitted
$hesklang['hidf']='Hidden inputs are not visible to customers on the Submit a ticket form (the value will still be visible on ticket details page if they are set as public). They behave as normal text fields for staff members.';
$hesklang['rcheck']='Do not select a default option';
$hesklang['refresh_page']='Refresh this page';
$hesklang['banip']='IPブロック';
$hesklang['del_kba']='Delete this article';
$hesklang['del_kbaa']='Permanently delete this article';
$hesklang['hni1']='HESK not installed yet?';
$hesklang['hni2']='It appears that this help desk has not been properly installed and configured yet.';
$hesklang['cf']='キャッシュ フォルダー';
$hesklang['e_cdir']='Hesk will not be able to parse emails or cache results unless the cache folder exists and is writable.';
$hesklang['step1']='Step 1';
$hesklang['step2']='Step 2';
$hesklang['dffs']='When download completes, delete the file from server';
$hesklang['fd']='Export file deleted from server';


// Added or modified in version 2.8.0
$hesklang ['TZ'] = 'タイムゾーン';
$hesklang ['thist17'] = '<li class = "smaller">%s | IMAPフェッチによって送信されました</ li> ';
$hesklang ['sir3'] = 'Invisible reCAPTCHA';
$hesklang ['invisible'] = 'invisible';
$hesklang ['rcpb'] = 'サイトキー';
$hesklang ['rcpv'] = 'シークレットキー';
$hesklang ['recaptcha_error'] = 'reCAPTCHASPAM保護を検証できませんでした。';
$hesklang ['imap_not'] = 'PHPはIMAPサポートでコンパイルされていません';
$hesklang ['imap_warning'] = 'ユーザー%1 $ sは、IMAPフェッチメールアドレスと同じメールアドレスを持っています:%2 $ s'; //%1 $ s =ユーザー名、%2 $ s =メールアドレス
$hesklang ['pop3_warning'] = 'ユーザー%1 $ sは、POP3フェッチメールアドレスと同じメールアドレスを持っています:%2 $ s'; //%1 $ s =ユーザー名、%2 $ s =メールアドレス
$hesklang ['fetch_warning'] = 'これにより、ユーザーの電子メール通知から新しいチケットが作成される電子メールループが発生する可能性があります。取得するメールアドレスは一意であり、他の人が使用しないようにする必要があります。 ';
$hesklang ['from_warning'] = 'HeskはSMTPサーバーを使用して電子メール通知を送信しています。あなたの＆quot;%1 $ s＆quot; ＆quot;%2 $ s＆quot;タブは次のように設定する必要があります:%3 $ s '; //%1 $ s = "From email" text、%2 $ s = "General" tab text、%3 $ s = email address
$hesklang ['can_view_ass_by'] = '他の人に割り当てたチケットを表示できます';
$hesklang ['can_privacy'] = 'チケットを匿名化できます';
$hesklang ['confirm_anony'] = 'このチケットを匿名化する';
$hesklang ['anon_selected'] = '選択したチケットを匿名化する';
$hesklang ['privacy_anon_info'] = '個人を特定できるすべてのデータとコンテンツをチケット（顧客名、電子メール、メッセージ、添付ファイル、IP ...）から削除しますが、統計のためにデータベースにチケットを保持します（忘れられる権利）。 ';
$hesklang ['success_anon'] = 'チケットは正常に匿名化されました';
$hesklang ['num_tickets_anon'] = '匿名化されたチケットの数:<b>%d </ b>';
$hesklang ['num_tickets_deleted'] = '削除されたチケットの数:<b>%d </ b>';
$hesklang ['anon_IP'] = '0.0.0.0'; //匿名化されたチケットのIP
$hesklang ['anon_name'] = '[顧客]'; //匿名化されたチケットの顧客名
$hesklang ['anon_email'] = ''; //匿名化されたチケットの顧客の電子メール
$hesklang ['anon_subject'] = '[Subject]'; //匿名化されたチケットのチケットサブジェクト
$hesklang ['anon_message'] = '[メッセージ]'; //匿名化されたチケットのチケットメッセージ
$hesklang ['thist18'] = '<li class = "smaller">%s | %sによって匿名化</ li> ';
$hesklang ['print_selected'] = '選択したチケットを印刷する';
$hesklang ['with_selected'] = '選択済み:';
$hesklang ['assign_selected'] = '選択した割り当て先:';
$hesklang ['assign_no'] = '所有者が選択されておらず、変更も加えられていません';
$hesklang ['assign_1'] = '選択したチケットは未割り当てに設定されています。';
$hesklang ['assign_2'] = 'チケットID%1 $ sが未割り当てに設定されました'; //%1 $ s =チケットの数値ID
$hesklang ['assign_3'] = '%1 $ sエラー:すでに%2 $ sに割り当てられています'; //%1 $ s =チケット追跡ID、%2 $ s =所有者名
$hesklang ['assign_4'] = '%1 $ sが%2 $ sに割り当てられました'; //%1 $ s =チケット追跡ID、%2 $ s =所有者名
$hesklang ['assign_5'] = '%1 $ sエラー:%2 $ sはチケットカテゴリにアクセスできません'; //%1 $ s =チケット追跡ID、%2 $ s =所有者名
$hesklang ['assign_log'] = '一括チケット割り当て結果:<br/> <br />割り当て済み:%1 $ s <br />エラー:%2 $ s <br /> <br />ログ:<br /> <pre>%3 $ s </ pre> '; //%1 $ s =割り当てられたチケットの数、%2 $ s =エラーの数、%3 $ s =ログ
$hesklang ['IP_addr'] = 'IPアドレス';
$hesklang ['moret'] = 'その他のオプション'; //その他のオプションボタンのタイトル
$hesklang ['btn_more'] = 'もっと'; //その他のオプションボタンのテキスト
$hesklang ['btn_print'] = '印刷';
$hesklang ['btn_edit'] = '編集';
$hesklang ['btn_lock'] = 'ロックチケット';
$hesklang ['btn_unlock'] = 'チケットのロックを解除';
$hesklang ['btn_tag'] = 'タグチケット';
$hesklang ['btn_resend'] = '電子メール通知を再送信する';
$hesklang ['btn_untag'] = 'タグ解除チケット';
$hesklang ['btn_import_kb'] = 'ナレッジベースにインポート';
$hesklang ['btn_anony'] = 'チケットの匿名化';
$hesklang ['btn_delt'] = 'チケットを削除';
$hesklang ['btn_delr'] = '返信を削除';
$hesklang ['ernf'] = '返信が見つかりません';
$hesklang ['tns'] = 'チケット通知が再度送信されました';
$hesklang ['rns'] = '返信通知が再度送信されました';
$hesklang ['fname'] = '名';
$hesklang ['export_selected'] = '選択したチケットをエクスポート';
$hesklang ['btn_export'] = 'Excel用のXMLにエクスポート';
$hesklang ['recaptcha'] = 'reCAPTCHA';

// Added or modified in HESK 3.0.0
$hesklang ['responses'] = 'Responses';
$hesklang ['team'] = 'チーム';
$hesklang ['banemail'] = 'メールブロック';
$hesklang ['sm_title'] = 'サービスメッセージ';
$hesklang ['et_title'] = 'メールテンプレート';
$hesklang ['tab_4'] = 'カスタムフィールド';
$hesklang ['reports_tab'] = 'レポートの実行'; //タブタイトル
$hesklang ['export'] = 'チケットのエクスポート'; //タブタイトル
$hesklang ['add_cat'] = '新しいカテゴリ';
$hesklang ['cat_name'] = '名前'; //カテゴリ名テーブルヘッダー
$hesklang ['cat_type'] = 'タイプ';
$hesklang ['cat_private'] = 'プライベート';
$hesklang ['cat_public'] = '公開';
$hesklang ['create_cat'] = 'カテゴリを保存';
$hesklang ['genl'] = 'リンクがクリップボードにコピーされました';
$hesklang ['delban'] = 'Unban';
$hesklang ['sm_content'] = 'コンテンツ';
$hesklang ['sm_settings'] = '設定';
$hesklang ['sm_save'] = '保存';
$hesklang ['sm_preview'] = 'プレビュー';
$hesklang ['wizard_back'] = '戻る'; //サイドバーの作成/編集ボタンでステップに戻ります
$hesklang ['wizard_next'] = '次へ'; //サイドバーの作成/編集ボタンでステップを進めます
$hesklang ['sm_go_to_settings'] = '設定に移動';
$hesklang ['sm_return_to_editing'] = '編集に戻る';
$hesklang ['email_tpl_title'] = 'タイトル';
$hesklang ['rdesc'] = '説明';
$hesklang['etfm']='One or more email templates are missing.<br>Make sure you upload all email template files inside your <i>/language/%s/emails</i> folder.';
$hesklang['etfw']='Some email templates are not writable.<br>
                    Make sure PHP has permission to write to all files inside your <i>/language/%s/emails</i> folder.<br>
                    On Unix servers you might need to CHMOD email templates to 666 (rw-rw-rw-)';
$hesklang['edit_email_template']='Edit email template';
$hesklang['et_save']='Save Changes';
$hesklang['status_custom_none']='No custom statuses. You can add them by clicking "New custom status" above.';
$hesklang['status_save']='Save';
$hesklang['err_no_settings_section']='No settings section was provided.';
$hesklang['sit']='Image Type';
$hesklang['q_q']='Question (HTML code is <span class="success">allowed</span>)';
$hesklang['q_a']='Answer';
$hesklang['admin_login']='Welcome! Please log in.';
$hesklang['this_field_is_required']='This field is required';
$hesklang['reset_your_password']='パスワードの再設定';
$hesklang['reset_password_instructions']='以下のフォームに必要事項を入力してください。パスワードをリセットするためのリンクをお送りします。';
$hesklang['enter_email']='Enter email';
$hesklang['passs']='Reset Password';
$hesklang['password_reset_check_your_email']='Check your email';
$hesklang['password_reset_link_sent']='We sent you a link to reset your password.';
$hesklang['back_to_login']='ログインに戻る';
$hesklang['inbox']='Inbox';
$hesklang['outbox']='Outbox';
$hesklang['m_new']='New Message';
$hesklang['m_from']='From'; // Mail "from" address
$hesklang['m_to']='To'; // Mail "to" address
$hesklang['m_sub']='件名'; // Mail subject
$hesklang['pager_first']='First';
$hesklang['pager_previous']='Prev';
$hesklang['pager_next']='Next';
$hesklang['pager_last']='Last';
$hesklang['new_team_member']='新しいチームメンバー';
$hesklang['role']='権限';
$hesklang['optional']='Optional';
$hesklang['edit_profile']='プロフィールを編集';
$hesklang['assigned_to']='Assigned to';
$hesklang['contact']='Contact';
$hesklang['unban_email']='Unban this email';
$hesklang['unban_ip']='Unban this IP';
$hesklang['addnote']='ノートを追加する';
$hesklang['show_previous_replies']='Show previous replies';
$hesklang['thist']='Ticket History';
$hesklang['type_your_message']='Type your message';
$hesklang['close_button_text']='Close';
$hesklang['create_new_ticket']='チケットを作成';
$hesklang['ktool']='Knowledgebase tools';
$hesklang['delete_article']='Delete article';
$hesklang['view_existing_tickets']='既存のチケットを表示する';
$hesklang['view_existing']='既存のチケットを表示する';
$hesklang['popart']='Top articles';
$hesklang['latart']='Latest articles';
$hesklang['sub_ticket']='チケットを送信';
$hesklang['how_can_we_help']='こんにちは!お困りのことがございますか？';
$hesklang['search_for_articles']='Search for articles';
$hesklang['submit_a_support_request']='サポートリクエストを送信する';
$hesklang['maximum_x_attachments']='最大%sつの添付ファイル'; // %s = max number of attachments (specified in settings)
$hesklang['verify_header']='スパム対策';
$hesklang['this_field_is_required']='This field is required';
$hesklang['ticket_details']='Ticket Details';
$hesklang['yes_title_case']='Yes';
$hesklang['no_title_case']='No';
$hesklang['rh']='Rated as helpful';
$hesklang['rnh']='Rated as not helpful';
$hesklang['ac']='Articles in this category';
$hesklang['sr']='Search Results';
$hesklang['no_results_found']='No Results Found';
$hesklang['ad']='Article Details';
$hesklang['hni3']='To install HESK, follow <a class="link" href="docs/">Instructions in the documentation</a>';
$hesklang['site_theme']='サイトテーマ';
$hesklang['test_theme_folder']='テーマフォルダーをテスト';
$hesklang['test_theme_folder_description']='Testing the theme folder for valid themes. Only themes that pass all tests are properly installed.';
$hesklang['err_site_theme']='Please select Hesk theme';
$hesklang['confirm']='Confirm';
$hesklang['confirm_deletion']='Confirm Deletion';
$hesklang['confirm_delete_status']='Are you sure you want to delete this custom status?';
$hesklang['critical']='重大な問題';
$hesklang['canned_add']='新しい定型文';
$hesklang['ticket_tpl_add']='新しいチケットテンプレート';
$hesklang['help_desk']='Help Desk'; // Displayed on staff sidebar menu

// Added or modified in HESK 3.1.0
$hesklang['TIMEAGO_LANG_FILE']='jquery.timeago.en.js'; // Name of the proper language file in folder /js/timeago/locales
$hesklang['tdis']='時間表示';
$hesklang['tdisd']='日にちと時間';
$hesklang['tdisa']='時間前（例：5時間前）';
$hesklang['nav_templates']='テンプレート'; // Admin panel navigation item
$hesklang['hide_replies']='チケットの返信を非表示にする';
$hesklang['hide_replies_no']='非表示にせず、常にすべての返信を表示する';
$hesklang['hide_replies_yes']='Hide all replies except the last:';
$hesklang['hide_replies_def']='Show the last staff reply and any subsequent customer replies';
$hesklang['reply_by']='Reply by'; // Reply by NAME
$hesklang['btt']='Back to Top';
$hesklang['lwidth']='チケットの幅を制限する';
$hesklang['lwidtall']='横幅をフルに使う';
$hesklang['lwidtpx']='最大幅（ピクセル）';
// 3-letter days of the week
$hesklang ['mon'] = 'Mon';
$hesklang ['tue'] = '火';
$hesklang ['wed'] = 'Wed';
$hesklang ['thu'] = 'Thu';
$hesklang ['fri'] = 'Fri';
$hesklang ['sat'] = 'Sat';
$hesklang ['sun'] = 'Sun';
$hesklang ['clear'] = 'Clear'; //フィールド値を削除します
$hesklang ['first_day_of_week'] = '0'; //週の最初の日; 0 =日曜日、1 =月曜日、2 =火曜日、..。
$hesklang ['cat_intro'] = 'ここで、カテゴリを管理できます。カテゴリは便利です
関連性によってチケットを分類するため（たとえば、「販売」、
「ハードウェアの問題」、「PHP / MySQLの問題」など）とのために
ユーザーをカテゴリーに割り当てる。 '; //これは3.0.xより前にあり、元に戻しました
$hesklang ['spam_req'] = '少なくとも1つのSPAM防止対策を有効にする必要があります！';
$hesklang ['modules'] = 'モジュール';
$hesklang ['modules_demo'] = 'このモジュールは現在%sでのみ使用可能です'; //%s = Heskクラウドリンク
$hesklang ['see_demo'] = 'ここでライブデモを試してください:%s'; //%s = Heskデモリンク
$hesklang ['statistics'] ['tab'] = '統計';
$hesklang ['statistics'] ['intro'] = 'このレポートは、ヘルプデスクの使用状況とスタッフのパフォーマンスに関する洞察を提供します。';
$hesklang ['statistics'] ['ntsp'] = '選択した期間にチケットがありません。';
$hesklang ['statistics'] ['pie_title_ro'] = 'オープンvs解決済みチケット';
$hesklang ['statistics'] ['open'] = 'Open';
$hesklang ['statistics'] ['resolved'] = '解決済み';
$hesklang ['statistics'] ['pie_title_as'] = 'オープンチケット:割り当て済みvs未割り当て';
$hesklang ['statistics'] ['ass'] = '割り当て済み';
$hesklang ['statistics'] ['unas'] = 'Unassigned';
$hesklang ['statistics'] ['pie_title_au'] = 'オープンチケット:回答済みvs未回答';
$hesklang ['statistics'] ['answered'] = 'Answered';
$hesklang ['statistics'] ['unanswered'] = 'Unanswered';
$hesklang ['statistics'] ['pie_title_so'] = '開いているチケットのステータス';
$hesklang ['statistics'] ['retic'] = 'チケット:';
$hesklang ['statistics'] ['chart_title_md'] = '月の1日あたりのチケット';
$hesklang ['statistics'] ['chart_title_wd'] = '平日あたりのチケット';
$hesklang ['statistics'] ['chart_title_hd'] = '1日あたりのチケット数 ';
$hesklang ['statistics'] ['chart_title_tfr'] = '最初のスタッフの返信までの時間';
$hesklang ['statistics'] ['chart_title_tfrc'] = '時間枠内に返信されたチケット';
$hesklang ['statistics'] ['chart_title_ttr'] = '送信からチケットの解決までの時間';
$hesklang ['statistics'] ['chart_title_ttrc'] = '時間枠内に解決されたチケット';
$hesklang ['statistics'] ['chart_title_sr'] = 'スタッフの返信';
$hesklang ['statistics'] ['chart_title_srt'] = 'チケットごとのスタッフの返信';
$hesklang ['statistics'] ['chart_title_srtr'] = 'チケットごとのスタッフの返信（解決されたチケットのみ）';
$hesklang ['statistics'] ['chart_title_srt1'] = 'チケットごとのスタッフの返信（少なくとも1つの返信があるチケット）';
$hesklang ['statistics'] ['ct_30'] = '30分 ';
$hesklang ['statistics'] ['ct_1h'] = '1時間';
$hesklang ['statistics'] ['ct_2h'] = '2時間';
$hesklang ['statistics'] ['ct_4h'] = '4時間';
$hesklang ['statistics'] ['ct_1d'] = '1日';
$hesklang ['statistics'] ['ct_2d'] = '2日';
$hesklang ['statistics'] ['ct_3d'] = '3日';
$hesklang ['statistics'] ['ct_1w'] = '1週間';
$hesklang ['statistics'] ['ct_wp'] = '> 1週間';
$hesklang ['statistics'] ['ct_1m'] = '1か月';
$hesklang ['statistics'] ['ct_mp'] = '> 1か月';
$hesklang ['statistics'] ['axis1'] = '返信されたチケットの%';
$hesklang ['statistics'] ['axis2'] = '解決されたチケットの%';
$hesklang ['statistics'] ['axis3'] = 'チケットの%';
$hesklang ['statistics'] ['axis4'] = '最初の返信までの時間';
$hesklang ['statistics'] ['axis5'] = '解決までの時間';
$hesklang ['statistics'] ['axis6'] = '返信数';
$hesklang ['statistics'] ['axis7'] = 'チケットの数';
$hesklang ['statistics'] ['axis8'] = 'Weekday';
$hesklang ['statistics'] ['axis9'] = 'Hour';
$hesklang ['statistics'] ['axis10'] = '月の日';
$hesklang ['statistics'] ['tr_0'] = '返信なし';
$hesklang ['statistics'] ['tr_1'] = '1 reply';
$hesklang ['statistics'] ['tr_2'] = '2 replies';
$hesklang ['statistics'] ['tr_5'] = '3-5 replies';
$hesklang ['statistics'] ['tr_10'] = '6-10 replies';
$hesklang ['statistics'] ['tr_99'] = '> 10件の返信';
$hesklang ['statistics'] ['average'] = 'Average';
$hesklang ['statistics'] ['atfr'] = '最初のスタッフの返信までの平均時間と分:';
$hesklang ['statistics'] ['attr'] = 'チケットを解決するための平均時間と分:';
$hesklang ['statistics'] ['about'] = 'about%s'; //おおよその時間; 「約5日3ハウス」
$hesklang ['statistics'] ['na'] = 'N / A';
$hesklang ['statistics'] ['trept'] = 'スタッフが返信したチケットの総数:';
$hesklang ['statistics'] ['trnr'] = 'スタッフの返信なしで解決されたチケットの総数:';
$hesklang ['statistics'] ['tsr'] = 'スタッフの返信総数:';
$hesklang ['statistics'] ['tsrt'] = 'チケットごとの平均スタッフ応答:';
$hesklang ['statistics'] ['tsro'] = 'チケットごとの平均スタッフ返信（少なくとも1人のスタッフ返信があるチケット）:';
$hesklang ['statistics'] ['tsrc'] = 'チケットを解決するために必要な平均的なスタッフの返信:';
$hesklang ['statistics'] ['tsrr'] = 'チケットを解決するために必要な平均的なスタッフの返信（少なくとも1人のスタッフの返信があるチケット）:';
$hesklang ['sep_1000'] = '、'; //数千のすべてのグループ間の区切り文字:1,000,000
$hesklang ['sep_dec'] = '。'; //完全な数値と10進数の間の区切り文字:0.99
$hesklang ['and_more'] = 'その他...'; //リストの最後のアイテム 

// Added or modified in HESK 3.2.0
$hesklang ['escalate'] ['tab'] = 'エスカレート'; //メニューリンク
$hesklang ['escalate'] ['page_title'] = 'チケットのエスカレーション'; //ページH2タイトル
$hesklang ['escalate'] ['intro'] = 'このモジュールは、時間どおりに出席されていないチケットをエスカレーションするのに役立ちます。';
$hesklang ['escalate'] ['feat1'] = 'チケットが割り当てられていない、返信されていない、または時間枠内に解決されていない';
$hesklang ['escalate'] ['feat2'] = 'チケットの期限が近づいており、チケットの期限が過ぎています';
$hesklang ['escalate'] ['feat3'] = 'チケットの優先度を自動的に変更し、チケットを再割り当てし、電子メール通知を送信します';
$hesklang ['escalate'] ['feat4'] = 'チケットのカテゴリ、所有者、ステータスに基づいてルールを適用します';
$hesklang ['escalate'] ['prefix'] = 'エスカレート:'; //件名のプレフィックスをメールで送信します。例: 「エスカレーション:[XXX-XXX-XXXX]テストチケット」
$hesklang ['escalate'] ['active_rules'] = 'アクティブなルール';
$hesklang ['escalate'] ['new'] = '新しいエスカレーションルール';
$hesklang ['escalate'] ['no_rules'] = 'エスカレーションルールはありません。 [新しいエスカレーションルール]をクリックして作成します。上のボタン。 ';
$hesklang ['escalate'] ['title'] = 'ルールタイトル';
$hesklang ['escalate'] ['titlet'] = '説明的なタイトル。例:1日以内に返信されなかったチケットを再割り当てします';
$hesklang ['escalate'] ['default_title'] = 'Rule by%1 $ s'; //デフォルトのルールタイトル; %1 $ s =ユーザー名
$hesklang ['escalate'] ['trigger'] = 'ルールトリガー';
$hesklang ['escalate'] ['trigt'] = 'このルールをトリガー（実行）する条件を設定します。';
$hesklang ['escalate'] ['hits'] = 'Hits'; //ルールがトリガーされた回数
$hesklang ['escalate'] ['step1'] = '条件'; //ルールを作成/編集するときのステップ1のタイトル
$hesklang ['escalate'] ['step2'] = 'アクション'; //ルールを作成/編集するときのステップ2のタイトル
$hesklang ['escalate'] ['step3'] = '適用先'; //ルールを作成/編集するときのステップ3のタイトル
$hesklang ['escalate'] ['delete'] = 'このルールを削除しますか？';
$hesklang ['escalate'] ['edit'] = 'エスカレーションルールIDの編集%1 $ s'; //%1 $ s =ルールID番号
$hesklang ['escalate'] ['ifat'] = 'サポートチケットは次のとおりです:'; //チケットが送信からX（分）以内に（解決されて）いない場合、（通知を再送信）
$hesklang ['escalate'] ['nrep'] = 'スタッフからの返信なし';
$hesklang ['escalate'] ['nrepc'] = '顧客からの返信なし';
$hesklang ['escalate'] ['nass'] = '割り当てられていません';
$hesklang ['escalate'] ['nres'] = '未解決';
$hesklang ['escalate'] ['ndue'] = '期限が近づいています';
$hesklang ['escalate'] ['odue'] = 'overdue';
$hesklang ['escalate'] ['within'] = 'Within:';
$hesklang ['escalate'] ['minutes'] = 'minutes';
$hesklang ['escalate'] ['hours'] = 'hours';
$hesklang ['escalate'] ['days'] = 'days';
$hesklang ['escalate'] ['weeks'] = 'weeks';
$hesklang ['escalate'] ['months'] = 'months';
$hesklang ['escalate'] ['years'] = 'years';
$hesklang ['escalate'] ['ofs'] = '送信中';
$hesklang ['escalate'] ['resend'] = '電子メール通知を再送信します:';
$hesklang ['escalate'] ['force'] = '常に送信し、スタッフの設定を無視します';
$hesklang ['escalate'] ['noforce'] = 'スタッフの通知設定を尊重する';
$hesklang ['escalate'] ['setpri'] = '優先度を次のように設定します:';
$hesklang ['escalate'] ['setsta'] = 'ステータスを次のように設定します:';
$hesklang ['escalate'] ['assto'] = 'チケットの割り当て先:';
$hesklang ['escalate'] ['asm'] = '別のスタッフメンバー';
$hesklang ['escalate'] ['notify'] = 'スタッフに通知...';
$hesklang ['escalate'] ['ato'] = '適用先:';
$hesklang ['escalate'] ['tic'] = 'カテゴリ内のチケット:';
$hesklang ['escalate'] ['tat'] = '割り当てられたチケット:';
$hesklang ['escalate'] ['tws'] = 'ステータス付きチケット:';
$hesklang ['escalate'] ['tall'] = 'このルールを既存および将来のチケットに適用します';
$hesklang ['escalate'] ['tfn'] = 'このルールを将来のチケットにのみ適用し、既存のチケットを無視します';
$hesklang ['escalate'] ['tfi'] = 'このルールは、IDが次の値よりも大きいチケットにのみ適用されます:';
$hesklang ['escalate'] ['save'] = 'ルールの保存';
$hesklang ['escalate'] ['e_tt'] = '時間は1から10000の間でなければなりません';
$hesklang ['escalate'] ['e_a'] = '一致するチケットに対して実行するアクションを少なくとも1つ選択してください';
$hesklang ['escalate'] ['nocat'] = '少なくとも1つのカテゴリを選択してください';
$hesklang ['escalate'] ['nouser'] = '少なくとも1人のユーザーを選択してください';
$hesklang ['escalate'] ['nostatus'] = '少なくとも1つのステータスを選択してください';
$hesklang ['escalate'] ['nocata'] = '%1 $ sはこれらのカテゴリにアクセスできません:'; //%1 $ s =ユーザー名
$hesklang ['escalate'] ['rule_added'] = '新しいルールが作成されました';
$hesklang ['escalate'] ['mdf'] = 'ルール設定が保存されました';
$hesklang ['escalate'] ['e_id'] = 'このIDのルールが見つかりません';
$hesklang ['escalate'] ['deleted'] = '選択したルールが削除されました';
$hesklang ['escalate'] ['edit_notice'] = 'ルールトリガーを変更しても、このルールによってすでにエスカレーションされているチケットには影響しません（ルールをリセットしない限り）。';
$hesklang ['escalate'] ['reset'] = 'このルールをリセット';
$hesklang ['escalate'] ['reset2'] = 'このルールをリセットしてもよろしいですか？<br> <br>ルールヒットは0になり、このルールに一致するチケットはすべて再度エスカレーションされます。';
$hesklang ['escalate'] ['reset3'] = '選択したルールがリセットされました';
$hesklang ['escalate'] ['log_title'] = 'ルール＃%1 $ s（%2 $ s）'; //チケット履歴ログで使用されます。 %1 $ s =ルールID、%2 $ s =ルールタイトル
$hesklang ['escalate'] ['thist1'] = '<li class = "smaller">%1 $ s | %2 $ sでエスカレーション:</ li> '; //チケット履歴ログで使用されます。 %1 $ s =日付、%2 $ s =ルールログのタイトル（上記）
$hesklang ['escalate'] ['thist2'] = '<li class = "smaller">%1 $ s | -優先度を%2 $ sに設定します</ li> '; //%1 $ s =日付、%2 $ s =優先度
$hesklang ['escalate'] ['thist3'] = '<li class = "smaller">%1 $ s | -%2 $ sに割り当てます</ li> '; //%1 $ s =日付、%2 $ s =所有者
$hesklang ['escalate'] ['thist4'] = '<li class = "smaller">%1 $ s | -スタッフへの通知を送信する</ li> ';
$hesklang ['escalate'] ['thist5'] = '<li class = "smaller">%1 $ s | -スタッフへの通知を送信します（強制）</ li> ';
$hesklang ['escalate'] ['thist6'] = '<li class = "smaller">%1 $ s | -エラー:%2 $ sはチケットカテゴリにアクセスできません</ li> '; //%1 $ s =日付、%2 $ s =所有者
$hesklang ['escalate'] ['thist7'] = '<li class = "smaller">%1 $ s | -エラー:%2 $ sにはチケットを表示する権限がありません</ li> '; //%1 $ s =日付、%2 $ s =所有者
$hesklang ['escalate'] ['thist8'] = '<li class = "smaller">%1 $ s | -エラー:このチケットを表示できる他のユーザーはいない</ li> '; //%1 $ s =日付
$hesklang ['escalate'] ['thist9'] = '<li class = "smaller">%1 $ s | -注意:優先度はすでに%2 $ sに設定されています</ li> '; //%1 $ s =日付、%2 $ s =優先度
$hesklang ['escalate'] ['thist10'] = '<li class = "smaller">%1 $ s | -注意:すでに%2 $ sに割り当てられています</ li> '; //%1 $ s =日付、%2 $ s =所有者
$hesklang ['escalate'] ['thist11'] = '<li class = "smaller">%1 $ s | -通知:%2 $ s </ li> '; //%1 $ s =日付、%2 $ s =ユーザーのリスト
$hesklang ['escalate'] ['thist12'] = '<li class = "smaller">%1 $ s | -ステータスを%2 $ sに設定します</ li> '; //%1 $ s =日付、%2 $ s =ステータス
$hesklang ['escalate'] ['thist13'] = '<li class = "smaller">%1 $ s | -注意:ステータスはすでに%2 $ sに設定されています</ li> '; //%1 $ s =日付、%2 $ s =ステータス
$hesklang ['escalate'] ['active'] = 'Active'; //ルールはアクティブ（ライブ）ですか？
$hesklang ['escalate'] ['activate'] = 'このルールをアクティブ化（使用を開始）';
$hesklang ['escalate'] ['activate'] = '選択したルールがアクティブ化されました'; //%1 $ s =ルールログのタイトル
$hesklang ['escalate'] ['deactivate'] = 'このルールを非アクティブ化します（使用を停止します）';
$hesklang ['escalate'] ['deactivate'] = '選択されたルールは非アクティブ化されました'; //%1 $ s =ルールログのタイトル
$hesklang ['escalate'] ['no_active'] = 'アクティブなエスカレーションルールはありません';
$hesklang ['escalate'] ['matched'] = '一致するチケットの数:%1 $ s'; //%1 $ s =チケットの数
$hesklang ['escalate'] ['tools'] = 'Tools';
$hesklang ['escalate'] ['test'] = 'このルールをシミュレートする';
$hesklang ['escalate'] ['testa'] = 'すべてのルールをシミュレートする';
$hesklang ['escalate'] ['testaa'] = 'すべてのアクティブなルールをシミュレートする';
$hesklang ['escalate'] ['testr'] = 'シミュレーション結果';
$hesklang ['escalate'] ['rsim'] = 'シミュレーションを繰り返す';
$hesklang ['escalate'] ['tbef'] = 'ルールを有効にする前に、「アクティブ」のチェックボックスをクリックしてルールをアクティブにする必要があります。列。<br> <br>
                               ルールテーブルの%1 $ s（このルールをシミュレート）アイコンをクリックして、各ルールを<strong>シミュレート</ strong>することを強くお勧めします。
                               有効化する前に、既存のチケットにどのように影響するかを確認してください。<br> <br>
                               <strong>アクティブなルールは%2 $ s分ごとに処理されます。チケットは、ルールごとに1回だけエスカレーションできます</ strong>。 '; //%1 $ s =アイコンに置き換え、%2 $ s =分数、通常は5以上
$hesklang ['escalate'] ['sim'] = 'シミュレーションモード、データベースへの変更なし';
$hesklang ['escalate'] ['sic'] = 'シミュレーション完了';
$hesklang ['escalate'] ['r'] = '[RULE]';
$hesklang ['escalate'] ['i'] = '[INFO]';
$hesklang ['multopt'] = 'ヒント:Ctrlキーを押しながら複数のオプションを選択します';
$hesklang ['desc_ticket_escalated'] = '（スタッフ）チケットがエスカレートされました'; //管理パネルのメールの説明
$hesklang ['ticket_formatting_staff'] = 'チケットフォーマット（スタッフ）';
$hesklang ['ticket_formatting_plaintext'] = 'プレーンテキスト';
$hesklang ['ticket_formatting_rich_text'] = 'リッチテキスト（HTML）';
$hesklang ['due_date'] = '期限';
$hesklang ['invalid_due_date'] = '無効な期日が入力されました。';
$hesklang ['thist19'] = '<li class = "smaller">%s |期日が%sによって%sに更新されました</ li> '; //%s =日付、新しい期日、ユーザーによる変更
$hesklang ['thist20'] = '<li class = "smaller">%s |期日は%sによって削除されました</ li> '; //%s =日付、ユーザーが変更を加える
$hesklang ['due_date_updated'] = 'チケットの期日が更新されました。';
$hesklang ['menu_kb_manage'] = '管理'; //左側の管理メニューナレッジベースの[管理]タブ
$hesklang ['menu_kb_view'] = '表示'; //左側の管理メニューナレッジベースの[表示]タブ
$hesklang ['a_select'] = 'すべて選択';
$hesklang ['a_deselect'] = 'すべて選択解除';
$hesklang ['a_toggle'] = 'すべてを切り替えます';
$hesklang ['ql_all'] = 'すべてのチケット';
$hesklang ['ql_alo'] = 'すべてのオープンチケット';
$hesklang ['ql_fit'] = 'フィルターされたチケット';
$hesklang ['ql_a2m'] = '私に割り当てられました';
$hesklang ['ql_a2o'] = '他の人に割り当てられました';
$hesklang ['ql_una'] = '未割り当て';
$hesklang ['ql_due'] = 'もうすぐ期限が切れます';
$hesklang ['ql_ovr'] = '期限切れ';
$hesklang ['set_ds'] = '「期限が近づいています」として表示'; //設定ページ（設定のタイトル）
$hesklang ['set_ds2'] = '期日の前日';
$hesklang ['not_aos'] = 'アクセスできる一部のオープンチケットは、フィルターが原因で表示されません。';
$hesklang ['ntoverdue'] = 'チケットは所有者に期限切れです:';
$hesklang ['ovdcron'] = '期限切れの通知を機能させるには、管理者がcronジョブを有効にする必要があります。';
$hesklang ['instructions'] = 'Instructions';
$hesklang ['desc_overdue_ticket'] = '（スタッフ）チケットの延滞';
$hesklang ['overdue_starting'] = '延滞チケット通知プロセスの開始';
$hesklang ['overdue_sim'] = 'シミュレーションモードでは、メールの送信とチケットの更新が無効になっています。';
$hesklang ['overdue_ticket_count'] = '期限切れの%sチケットが見つかりました。'; //%s =チケットの数
$hesklang ['overdue_finished'] = 'Finished OverdueTickets。 %sのメールが送信されました。 %sメールの送信に失敗しました。 '; //%s =成功したメール、失敗したメール
$hesklang ['admin_css'] = '管理者CSS';
$hesklang ['admin_css2'] = '管理パネル用の追加のカスタムスタイルファイルをロードします';
$hesklang ['noval_cert'] = 'サーバー証明書を検証しません';
$hesklang ['chg_cat'] = 'クリックしてチケットカテゴリを変更します';
$hesklang ['tlan'] = 'チケット言語';
$hesklang ['uue'] = '2人以上のスタッフが同じメールアドレスを持っています。ユーザーごとに一意のメールアドレスを設定することをお勧めします。 ';
$hesklang ['flood'] = '洪水制限';
$hesklang ['e_flood'] = 'おっと、あなたは最近返信を送信しました。返信のフラッディングを防ぐために、このリクエストを停止しました。 ';
$hesklang ['cookies'] = 'Cookies';
$hesklang ['ukey'] = 'URLアクセスキー'; // URLを介して特定のファイル（cronジョブなど）にアクセスするために必要なキー
$hesklang ['ukeyg'] = 'ランダムなURLアクセスキーを生成します';
$hesklang ['ukeym'] = 'エラー:このファイルをHTTP経由で実行するには、リクエストにURLアクセスキーを含める必要があります。例:';
$hesklang ['ukeyw'] = 'エラー:間違ったURLアクセスキー';

// DO NOT CHANGE BELOW
if (!defined('IN_SCRIPT')) die('PHP syntax OK!');
